### ISSUE TITLE
Adding support for the OpenGEX format

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#331] opened 2014-08-16 13:22 UTC
Please consider adding support for the OpenGEX format:

http://opengex.org/

**Comment by elect86** [comment] 2015-02-23 09:09
I have in mind to port assimp to java, a sort of jAssimp

How does it sound to you, guys?

**Comment by acgessler** [comment] 2015-02-23 10:05
We do already have Assimp-JNI (new) and jassimp (old) (see the ports folder). In both cases I am not up to date with what the respective status is, but consider helping out on either of them instead of rolling your own :-)

**Comment by elect86** [comment] 2015-02-26 08:21
I saw them, but they dont seem fully functioning, especially the jassimp.. whre could I ask the updated status?

**Comment by elect86** [comment] 2015-02-27 17:46
I just started to write the porting, anyone who wanna help is very welcome

https://github.com/elect86/jAssimp

**Comment by acgessler** [comment] 2015-02-27 19:04
FYI: This thread has a different topic (OpenGEX in Assimp). Maybe want to open a new issue for it?

Rewriting the importers in Java seems like a very lengthy endeavour. I'm not up to date what the status of the two existing bindings is, but it will be significantly less work to revive them. None of them attempts to re-write everything in Java, it's just glue to make the C-API available from Java. Of course this involves a dependency onto platform-specific, native libraries to be deployed with your Java application.

**Comment by erlend-sh** [comment] 2015-02-28 11:43
Back on topic, @kimkulling has been doing a great (and stealthy!) deal of work on an OpenDDL parser:

https://github.com/kimkulling/openddl-parser

Care to comment on how far along you are Kim? I started pointing other C++ gamedevs in your direction as soon as I found out about it :)

**Comment by kimkulling** [comment] 2015-02-28 15:31
I am currently doing a lot of debugging. So it is already in use for the OpenGEX-importer ( check my feature branch ) but I am still dealing with a lot of bugs ( as usual ). And thanks for the commercials :+1:

**Comment by elect86** [comment] 2015-03-01 14:20
@acgessler thanks for the contact suggestion :)

**Comment by reduz** [comment] 2015-03-01 15:34
I will likely start implementing OpenGEX in Godot the next months, so will
be bothering you all by then


On Sun, Mar 1, 2015 at 11:20 AM, Giuseppe Barbieri <notifications@github.com

**Comment by jdduke** [comment] 2015-03-08 20:35
@kimkulling if you're having issues with the importer, I wonder if we should reconsider leveraging the OpenGEX import template. The rough Assimp importer I whipped up that used the template was both brief in implementation and in time to implement. Moreover, should the standard evolve we'd get many of the changes for "free", or at least cheaply. Just a thought, as it's been nearly 6 months.

**Comment by kimkulling** [comment] 2015-03-09 08:02
More than 6 months I guess.Of course we can start using this one if the importer is urgently needed. Never the less: at the moment I am working on transforming the parsed data to our asset-importer format and this job must be done with the reference-importer as well. So I don't see so much benefit here by using another parser.

But I can push my current work to master and you could help me doing the transformation. This would be really useful. 

I don't think that I will have more time in the next months because our sun was born some days ago and he will keep me busy as well together with our older daugther :-).

**Comment by kimkulling** [comment] 2015-03-09 09:20
Update: At the moment I mostly working on the transformation from parsed data into the asset importer format. So any help would be very welcome here. The parser works for me and I am only doing some bugfixing at this moment.

So what do you think about pushing my work on master to get some help?

Kimmi

**Comment by jdduke** [comment] 2015-03-09 18:47
First off, congratulations on the new arrival!

If you can point me to your current work (is it a branch off the main assimp trunk?), I could probably work on it there, or branch it and continue working. Otherwise I suppose we could push it to master but have it disabled by default?

**Comment by acgessler** [comment] 2015-03-10 15:09
Offtopic, but congratulations as well :-)

**Comment by kimkulling** [comment] 2015-03-10 18:55
Thanks a lot!

**Comment by kimkulling** [comment] 2015-03-11 19:25
I will mark the importer as experimental, exclude it from the common build and publish it to master.

**Comment by jdduke** [comment] 2015-03-31 14:14
I see that Kim is continuing work on the feature, so I guess I'll stop what I was doing. 

FWIW, I have a functional version of OpenGEX support here: https://github.com/jdduke/assimp/tree/opengex_support. It doesn't yet support animations, but most everything else *should* work (though it's thoroughly untested). The key difference from master is that it's built on the standard OpenGEX import template (with a few tweaks to make C++11 features optional), instead of Kim's custom OpenDDL parsing code.

**Comment by acgessler** [comment] 2015-03-31 15:33
It's unfortunate that we have redundant work here. What was the reasoning for starting the parser from scratch?

**Comment by kimkulling** [comment] 2015-03-31 17:52
As I wrote before:
- no version control for the reference parser
- I was interested in trying it on my own, so just for fun

**Comment by kimkulling** [comment] 2015-03-31 18:17
@jdduke: great work! So how do we want to continue?

**Comment by jdduke** [comment] 2015-03-31 18:27
I don't have a strong opinion. It's possible I could integrate some of the assimp glue with your parser. However, the glue I wrote turned out to not be a whole ton of code (most of the heavy lifting was in the parser and structure validation already provided by the import template) so it's not a big loss to me if we proceed without it. You have more invested here, so I'll defer to your preference :).

I guess my only hesitation in using the custom parser is testing and maintenance, but if that's something you (and/or others) can commit to it may not be a problem.

**Comment by acgessler** [comment] 2015-03-31 18:53
We shouldn't throw away existing work, to the contrary, keep up the good work :-)

If maintenance for openddl-parser is secured, let's go for it. #454 (@turol) seems to have surfaced a few more things that probably apply to openddl-parser itself, less the OpenGEX importer code within assimp.

More generally, once opengex support is good to go (your determination ;-)), we should make another release. I hope to have the regression suite issues addressed by then so we can call it a good step forward in both format support, and quality.

**Comment by kimkulling** [comment] 2015-03-31 21:17
You can find the OpenDDL-parser here: https://github.com/kimkulling/openddl-parser . I will maintain it.

Thanks for the number, I also saw it and I will take a look onto it.

Regrading determination of the OpenGEX-support: it is a nice fact that I am currently in parental leave and have some more time for the importer. Hopefully we have some stable state in the next couple of weeks.

**Comment by kimkulling** [comment] 2015-06-25 22:08
Is there on master!

**Closed** 2015-06-25 22:08 UTC

**Comment by reduz** [comment] 2015-06-26 14:33
Question out of curiosity. Is OpenGEX still maintained? I know the author
abandoned the C4 engine and i couldn't find a github page for the export
plugin source code.

**Comment by kimkulling** [comment] 2015-06-26 15:49
The latest version of the C4-Engine was release on April this year: http://www.terathon.com/forums/viewtopic.php?f=2&t=14160

And OpenGex:
Version 1.1.2. 10-Dec-2014

Expanded the Morph structure to have an optional base property.
Added explanation of morphing calculations to the description of the MorphWeight structure.

**Comment by reduz** [comment] 2015-06-26 15:53
Yes I know, but C4 is discontinued, and the exporters can't be found for
contribution on github so we don't know if they are maintained any longer

**Comment by kimkulling** [comment] 2015-06-26 16:48
As far as I know the OpenGEX format will maintained without an active github-project by its author.

**Comment by EricLengyel** [comment] 2015-06-26 17:30
Hi --

Yes, OpenGEX is still being maintained, and the source code is available on opengex.org.

Also, the C4 Engine was not abandoned. It is being developed full time and used for our own internal projects. However, it simply isn’t cost-effective for us to license it out any more.

-- Eric Lengyel
