### ISSUE TITLE
Can't load "FBX models with Skeletal animation" properly

### ISSUE THREAD

**Issue by papertype** [assimp/assimp#1297] opened 2017-06-03 17:23 UTC
I'm trying to make a simple model viewer with Assimp to show "FBX models with Skeletal animation".
But results are always broken. Bones are crashed.

Also, neither the latest "assimp_viewer" nor "Open 3D Model Viewer" can load them properly.

This is one of the samples I tested.
https://clara.io/view/2c296545-1204-4fc3-b470-c39bec65e86c

Collada (.dae) format of this model can be loaded somewhat properly:
![gunbot-dae](https://cloud.githubusercontent.com/assets/29165551/26755635/210f494c-48cc-11e7-9b06-d962a7734e92.png)
![viewer-dae](https://cloud.githubusercontent.com/assets/29165551/26755639/35d1d98a-48cc-11e7-9491-69f53e4bdb1b.png)

But FBX format:
![gunbot-fbx](https://cloud.githubusercontent.com/assets/29165551/26755641/3be8a128-48cc-11e7-9525-beead4736031.png)
![viewer-fbx](https://cloud.githubusercontent.com/assets/29165551/26755643/41839aca-48cc-11e7-9b4c-6c8091be0f95.png)

I couldn't find any FBX models with Skeletal animation which can be loaded properly with Assimp.
Is this a bug, or is there a way to fix this?

**Comment by vexe** [comment] 2017-06-10 07:05
I was able to load mine just fine. I would recommend you look at this example https://github.com/ccxvii/asstools/blob/master/assview.c

**Comment by papertype** [comment] 2017-06-10 09:48
I'm testing with free FBX models like above (https://clara.io/view/2c296545-1204-4fc3-b470-c39bec65e86c). Were you able to load and play this animation with your program? Open3mod and assimp_viewer can't. Autodesk FBX Review can.

**Comment by vexe** [comment] 2017-06-10 15:50
Yeah doesn't play correctly with open3viewer. Looks like a corner case in Assimp's importer. Few things to try:

- Import the model in 3dsmax, and try exporting with different settings
- I've had issues like this before and they mostly evolve around export settings, different 3d packages have different X/Y/Z directions, no standards. Plus you could export your model with something crazy like -X being their forward axis! So many cases to handle Assimp probably missed or mis-handled some of them.
- In assview.c, try compiling and running that, load the model, mess with the import flags, in the beginning of the program see if you could find something useful. Then try and manually flip the vertices after you loaded them, swap Z/Y see if it loads any different maybe that will lead you to some clues as to what's actually happening
- If all fails, you'd need the author to debug this.

**Comment by nem0** [comment] 2017-06-26 12:52
@papertype I am not 100% it's the same issue, but I can't load some fbx animations properly too. The problem is Assimp converts data to its own representation which is common for all formats. But some FBX features are lost in the process / work differently. I had to use Autodesk's FBX SDK because of it.

**Comment by rickomax** [comment] 2017-07-15 13:47
There is a known bug about relational transform somewhere else on this list. The most important FBX bug for me.

**Comment by kimkulling** [comment] 2017-07-31 18:23
Will be fixed soon. Much to much people have issues with this!

**Comment by ObsydBT** [comment] 2017-09-06 21:02
Having the same issue. Would love to see this fixed! Thank you for your work!

**Comment by mrEscen** [comment] 2017-09-13 08:25
How is this issue progressing? Did some test implementing Autodesk's FBX SDK but I prefer assimp. This part of the project is frozen for now but can you tell anything about progress for upcoming fixes.

**Comment by mesilliac** [comment] 2018-02-23 07:54
Can anyone test if this is fixed in assimp master? Geometric transformations should now be applied correctly.

**Comment by kimkulling** [comment] 2020-01-28 18:28
Shall work now.

**Closed by kimkulling** 2020-01-28 18:28 UTC
Labels: Bug
