### ISSUE TITLE
Continuous integration fails randomly due to connection issues

### ISSUE THREAD

**Issue by RevoluPowered** [assimp/assimp#2811] opened 2019-12-05 16:01 UTC
Attached log from AppVeyor https://github.com/assimp/assimp/pull/2802

Issue tends to go away if you force push

```Time Elapsed 00:09:20.10
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, String method, Byte[] data)
   at Appveyor.BuildAgent.Api.RestBuildServices.AddCompilationMessage(String message, Nullable`1 category, String details, String fileName, Nullable`1 line, Nullable`1 column, String projectName, String projectFileName)
   at Appveyor.MSBuildLogger.AppveyorLogger.SendCompilationMessage(BuildMessageCategory category, String message, String code, String file, Int32 lineNumber, Int32 columnNumber, Int32 projectId)
   at Appveyor.MSBuildLogger.AppveyorLogger.eventSource_WarningRaised(Object sender, BuildWarningEventArgs e)
   at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.WarningRaisedHandler(Object sender, BuildWarningEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseWarningEvent(Object sender, BuildWarningEventArgs buildEvent)
Command exited with code 1
(new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testout.xml))```

**Comment by kimkulling** [comment] 2019-12-08 08:05
I know. This annoying issue seems to be not-solvable from appveyor side. Does anyone know a better CI-solution for windows?

**Comment by turol** [comment] 2019-12-09 13:53
GitHub actions might be able to do it.

**Comment by RevoluPowered** [comment] 2019-12-09 20:54
I can try to look into this as I have CI related stuff to do for work

**Comment by kimkulling** [comment] 2019-12-10 07:49
That would be great. I tried to investigate this annoying issue some months ago but I stucked caused by the lack on time.

**Comment by kimkulling** [comment] 2019-12-10 07:50
And Github-actions is definitely an option to go for. I haven't tried them out until now. Does anyone made some experiences with them?

**Comment by kimkulling** [comment] 2020-06-23 12:07
We switched to Github-Actions. So I can close this topic.

**Closed by kimkulling** 2020-06-23 12:07 UTC
Labels: Bug, Build
