### ISSUE TITLE
Cannot load Blender 2.9 file

### ISSUE THREAD

**Issue by sherief** [assimp/assimp#3407] opened 2020-09-27 12:05 UTC
**Describe the bug**
Code at current Top of Tree ( 22dd53a ) fails to load the default Blender file with a single cube.

**To Reproduce**
- Open Blender (I used 2.90.1). You should be at the general start file with a single cube, a light, and a camera
- Without changing anything just save the file as-is
- Try to load via assimp, it throws "Expected at least one object with no parent" from BlenderLoader.cpp:350

**Expected behavior**
File should load normally. Default / startup files created with Blender 2.8 seem to load fine.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10, x64

**Smartphone (please complete the following information):**
N/A

**Additional context**
None.

**Comment by jaredthirsk** [comment] 2021-03-01 22:43
Looks like a duplicate of #3316, which is in progress on the roadmap: https://github.com/assimp/assimp/projects/4#card-55129231

**Closed** 2021-05-01 10:00 UTC
Labels: Bug, Blender
