### ISSUE TITLE
Xcode 8.3 beta 2 won't compile assimp

### ISSUE THREAD

**Issue by gonchar** [assimp/assimp#1169] opened 2017-02-07 16:51 UTC
Hello, 

I started to receive this error. Seems like current workaround is to remove packed declarations for structures.

`assimp/include/assimp/vector3.inl:149:15: Taking address of packed member 'x' of class or structure 'aiVector3t<float>' may result in an unaligned pointer value`

**Comment by kimkulling** [comment] 2017-02-07 18:31
Could you please specify which compiler is in use by the IDE? Thanks a lot!

**Comment by turol** [comment] 2017-02-07 18:48
Xcode uses some version of clang but apple makes it real damn hard to find out which version exactly.

In related news, this code is completely bogus:
```
TReal x, y, z;
```
Since x, y and z are not in an array it's UB to try to get at y and z by adding stuff to x. The compiler would be well within its rights to decide that `operator[]` can't possibly read from anything but x and always return the value of x.

The correct code would be:
```
union {
  TReal values[3];
  struct {
    TReal x, y, z;
  };
};
```
and then use `values[i]` in `operator[]`. This would be an API change and I think some compilers complain about anonymous struct/union.

**Comment by gonchar** [comment] 2017-02-14 22:41
The issue here is the taking of member address in PACK_STRUCT. As I understand, this is just not safe code, and the latest XCode clang compiler shows it as an error by default.

**Comment by turol** [comment] 2017-02-15 07:29
That's an issue but not the only issue. Even if you fix it there will still be UB because of the invalid pointer arithmetic.

**Comment by gonchar** [comment] 2017-02-19 21:10
could you please point a place where such arithmetic happens in assimp? I couldn't find it

**Comment by turol** [comment] 2017-02-19 21:19
https://github.com/assimp/assimp/blob/master/include/assimp/vector3.inl#L149

"x" is not part of an array (x is defined in https://github.com/assimp/assimp/blob/master/include/assimp/vector3.h#L128) so adding stuff to its address and dereferencing is UB.

**Comment by kimkulling** [comment] 2017-02-21 08:35
Hi,

`union {
  TReal values[3];
  struct {
    TReal x, y, z;
  };
};`

This code is not permitted for C++11, only for C.

We can introduce something like:

`union vector3 {
  TReal values[3];
  struct {
    TReal x, y, z;
  };
};`

See http://stackoverflow.com/questions/2253878/why-does-c-disallow-anonymous-structs-and-unions .

**Comment by kimkulling** [comment] 2017-02-21 09:00
And another option would be: just remove the []-operator.

**Comment by turol** [comment] 2017-02-21 09:08
Both of those break the API and so require a major version bump. We could try this
```
switch (i) {
case 0:
    return x;

case 1:
    return y;

case 2:
    return z;
}
```

and hope the compiler optimizes it away.

**Comment by kimkulling** [comment] 2017-02-21 16:30
Closed by  c3bb2b6.

**Comment by turol** [comment] 2017-02-22 20:57
aiColor3D probably has the same issue. aiMatrix* types suffer from the UB issue as well.

On Linux clang 4.0rc2 doesn't trigger this warning even if I explicitly specify  -Waddress-of-packed-member. It looks like at some point this was an error instead of a warning and I'm not sure if it made it in official clang 4.0. @gonchar is it an error or a warning on Xcode?

**Comment by kimkulling** [comment] 2017-02-23 14:18
Ok, so let's reopen the issue.

**Comment by gonchar** [comment] 2017-02-23 22:35
yes, it was the same there as well

**Comment by kimkulling** [comment] 2017-03-01 08:51
I am currently working on a fix. My idea is to use an array of vector3 / vector4. I am currenty investigating how much effort and changes this will cause.

**Comment by kimkulling** [comment] 2017-03-31 11:52
To much changes, I will try to integrate a fix this weekend.

**Comment by msc-** [comment] 2017-04-08 05:00
This is the same problem as issue #1057 and was fixed by https://github.com/assimp/assimp/commit/d4223d1fce2e9edd8d4c1be1fa48f70042b71876.

The problem for me is that there hasn't been a release of assimp since that fix. I have had to take the latest headers from Git. Unfortunately they cause a warning with gcc 6.2. I'll open another issue about that.

**Comment by msc-** [comment] 2017-04-08 05:08
> I'll open another issue about that.
Done. It's #1225.

**Comment by kimkulling** [comment] 2017-06-07 19:06
The xcode CI build works. So if this is still an issue please just reopen.

**Comment by mvidiassov** [comment] 2018-01-17 12:42
I am getting the same warning as triggered this issue:
Taking address of packed member 'x' of class or structure 'aiVector2t<float>' may result in an unaligned pointer value.
The cause seems to be that [https://github.com/assimp/assimp/commit/c3bb2b66ac94d8e75396210268d7f6e82286eaa6](url) only fixed 3d vectors. 
Why not to apply the same approach to 2d?
Version info: Assimp 4.1.0, Xcode 9.1, MacOS 10.12.6

**Comment by kimkulling** [comment] 2019-02-06 20:07
Shall be fixed now.

**Closed by kimkulling** 2019-02-06 20:07 UTC
