### ISSUE TITLE
Bug: possibly dangling reference to a temporary [-Werror=dangling-reference]

### ISSUE THREAD

**Issue by SamuelZy810** [assimp/assimp#5383] opened 2023-12-17 18:09 UTC
The error occurs while compiling, 

C:/Users/samue/Desktop/assimp/code/AssetLib/FBX/FBXParser.cpp:670:20: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  670 |     const Element& a = GetRequiredElement(scope,"a",&el);
      |  

I am using gcc compiler (version 13).

Is there any branch that fixex this error or possibly any compiler that has no problem compiling this library?

**Comment by turol** [comment] 2023-12-18 13:37
Duplicate of https://github.com/assimp/assimp/issues/5145

**Closed by turol** 2023-12-18 13:37 UTC
Labels: Bug
