### ISSUE TITLE
aiGetImporterDesc: wrong name mangling in libassimp.so [Linux]

### ISSUE THREAD

**Issue by Manuel-Koenig** [assimp/assimp#3685] opened 2021-03-03 00:12 UTC
Description:
I expected the symbol name in libassimp.so to be "aiGetImporterDesc", but it is "_Z17aiGetImporterDescPKc".
All other symbol names are the same as their corresponding function names, this is the only exception.
This causes a symbol loading error.

This is the case in the current 5.0.1 Manjaro and ArchLinux packages.

You can see this from the output of the command

nm -D /usr/lib/libassimp.so | grep aiGetImporterDesc

Possible cause of the error:
All exported functions are declared with the ASSIMP_API prefix, and aiGetImporterDesc is the only function
that also uses the C_STRUCT macro on the return type, so I expect this macro to cause the error.
See code/Common/Assimp.cpp for this.

**Comment by RichardTea** [comment] 2021-03-03 10:05
Please check if this is still problematic for the current head.
The 5.0.1 release is very old.

**Comment by Manuel-Koenig** [comment] 2021-03-03 10:07
This is what the situation with the currently distributed packages is. And on the project page it still looks like 5.0.1 is the latest release, so there is nothing newer to test.

**Comment by Manuel-Koenig** [comment] 2021-03-03 10:17
I compiled the current head, and the problem is still there.

**Comment by Manuel-Koenig** [comment] 2021-03-03 10:26
Another possibility is that the name mangling is actually correct, but the binding I am using is not looking for the correctly mangled symbol name. But it's suspicious that all other symbol names are the same as the function name, without any special mangling.

**Comment by turol** [comment] 2021-03-03 13:16
It's caused by `importerdesc.h` missing the appropriate `__cplusplus` / `extern "C"` guards.

**Comment by kimkulling** [comment] 2021-03-09 17:27
Closed by https://github.com/assimp/assimp/pull/3687, thanks for the report and the fix.

**Closed by kimkulling** 2021-03-09 17:27 UTC
