### ISSUE TITLE
Bug: Analyze the model and obtain that UV is empty

### ISSUE THREAD

**Issue by liuzhoulong** [assimp/assimp#5116] opened 2023-06-02 07:07 UTC
**Describe the bug**
Hi. I used assimp5.0.1 to load the miku model and it was able to obtain the correct UV coordinates(mTextureCoords) and display them normally, but using assimp5.2.5 to load the miku model resulted in the display being incorrect due to the null UV coordinates(mTextureCoords) obtained.

**To Reproduce**
After loading the model, use OpenGL to display it.

**Expected behavior**
Miku model can display normally.

**Screenshots**
Using 5.0.1:
![miku](https://github.com/assimp/assimp/assets/28398304/103c3d68-ce14-47cb-b783-d59a3e1a0998)

Using 5.2.5:
![miku5 2 5](https://github.com/assimp/assimp/assets/28398304/cd626b3e-c67f-4161-a854-a524d3af1ef4)

**Platform (please complete the following information):**
 - OS: Windows10
 - Version: Assimp5.0.1 and Assimp5.2.5

**Additional context**
The model I used:
[Miku.zip](https://github.com/assimp/assimp/files/11648724/Miku.zip)

**Comment by darktjm** [comment] 2023-09-09 05:37
9e46fca9a911db010a6be87780073336785efccb
```
FBX: length of input data unexpected for ByVertice mapping: 2733, expected 8643
FBX: length of input data unexpected for ByVertice mapping: 2733, expected 8643
```
```
--- a/code/AssetLib/FBX/FBXMeshGeometry.cpp
+++ b/code/AssetLib/FBX/FBXMeshGeometry.cpp
@@ -453,7 +453,7 @@ void ResolveVertexDataArray(std::vector<T>& data_out, const Scope& source,
         std::vector<int> uvIndices;
         ParseVectorDataArray(uvIndices,GetRequiredElement(source,indexDataElementName));
 
-        if (uvIndices.size() != vertex_count) {
+        if (uvIndices.size() != mapping_offsets.size()) {
             FBXImporter::LogError("length of input data unexpected for ByVertice mapping: ",
                                   uvIndices.size(), ", expected ", vertex_count);
             return;
```

**Comment by darktjm** [comment] 2023-09-16 21:53
No comment in over a week? Expecting me to file a pull request (not going to happen; just fix it yourself and don't bother giving credit for a trivial fix)?  Nobody monitoring "old" issues becuase github wisely chose "last added" rather than "last updated" as the default sort criteria?  Secret rewrite of the FBX importer in progress?  Nobody interested in fixing FBX issues any more, given that it's so broken since 5.0.1 anyway (e.g. numerous anim issues since at least 14b8d1242b0f32fef9dd8ace0a1d4e8cbd20d88c)?  I'd try harder to fix them myself, but I have other priorities, and for now, I have other ways of dealing with FBX files (I can still get the FBX SDK, at least, and sometimes, if the planets are correctly aligned, Blender actually successfully converts them as well, with only a little bit of manual intervention).  Also, I can't report fixes any more after MS boots me off of github.

**Comment by stephengold** [comment] 2023-10-27 23:59
I'm able to reproduce this issue using the "Miku.zip" model provided by the OP.

I'm also seeing "length of input data" issues while importing other FBX models:
```console
Error, T0: FBX: length of input data unexpected for ByPolygon mapping: 1076, expected 972
```
so there may be similar issues elsewhere in AssetLib/FBX.

**Comment by kimkulling** [comment] 2023-12-04 19:50
Sorry for my late response. I am rare on time and I am overwhelmed by the number of open topics.

**Comment by kimkulling** [comment] 2023-12-04 19:57
Closed by https://github.com/assimp/assimp/pull/5333

**Closed by kimkulling** 2023-12-04 19:57 UTC
Labels: Bug
