### ISSUE TITLE
Error building with mingw

### ISSUE THREAD

**Issue by thisisleobro** [assimp/assimp#3251] opened 2020-05-31 04:54 UTC
I am using gcc version 7.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project) on windows 10
and i get the following error when i try to compile assimp with cmake. I dont know how i should proceed. For what i read lib rt is linux only. Any help please??

Shared libraries enabled
Looking for ZLIB...
Checking for module 'zzip-zlib-config'
  No package 'zzip-zlib-config' found
Found ZLIB: optimized;C:/dev/zlib/lib;debug;C:/dev/zlib/lib
Checking for module 'minizip'
  No package 'minizip' found
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (rt) does
  not match the name of the calling package (RT).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake-modules/FindRT.cmake:19 (find_package_handle_standard_args)
  code/CMakeLists.txt:1039 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find rt (missing: RT_LIBRARY) 
INFO Hunter enabled or RT-extension not found. glTF import/export will be built without Open3DGC-compression.
Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
Disabled importer formats:
Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF ASSJSON STEP
Disabled exporter formats:
Configuring done

**Comment by outfrost** [comment] 2020-05-31 23:26
That's not an error, but a pretty normal CMake output, as far as I can tell.

CMake on its own won't compile anything, because it only generates the build instructions for `make`. To build a project after running CMake, you need to use `make`.

**Comment by thisisleobro** [comment] 2020-06-01 02:16
> That's not an error, but a pretty normal CMake output, as far as I can tell.
> 
> CMake on its own won't compile anything, because it only generates the build instructions for `make`. To build a project after running CMake, you need to use `make`.

Ok i just assumed there was an error because of the red word. 
I generate i makefile bu then i get:
```
Scanning dependencies of target IrrXML
[  0%] Building CXX object contrib/irrXML/CMakeFiles/IrrXML.dir/irrXML.cpp.obj
[  0%] Linking CXX static library ..\..\lib\libIrrXML.a
[  0%] Built target IrrXML
Scanning dependencies of target assimp
[  0%] Building CXX object code/CMakeFiles/assimp.dir/Common/Assimp.cpp.obj
[  1%] Building CXX object code/CMakeFiles/assimp.dir/CApi/CInterfaceIOWrapper.cpp.obj
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseImporter.cpp.obj
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseProcess.cpp.obj
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/PostStepRegistry.cpp.obj
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.obj
In file included from C:/Users/user/STAGE/assimp/code/AssetLib/3DS/3DSLoader.h:55:0,
                 from C:\Users\user\STAGE\assimp\code\Common\ImporterRegistry.cpp:63:
C:/Users/user/STAGE/assimp/code/AssetLib/3DS/3DSHelper.h:325:0: error: ignoring #pragma warning  [-Werror=unknown-pragmas]
 #pragma warning(disable : 4315)

cc1plus.exe: all warnings being treated as errors
make[2]: *** [code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.obj] Error 1
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mydearyoungsnow** [comment] 2020-06-19 01:18
I have the same problem as you. The key to the problem is "all warnings being treated as errors". You can modify this file to solve the problem: "assimp_master\build\code\cmakefiles\assimp.dir\flags.make”(the build directory is created by myself to store the files generated by cmake), and the "CXX_FLAGS" last -Werror changed to -Wno-error.

**Comment by kimkulling** [comment] 2020-07-09 07:51
Closed by https://github.com/assimp/assimp/pull/3314

**Closed by kimkulling** 2020-07-09 07:51 UTC
