### ISSUE TITLE
Missing some meshes(objects) after processing with assimp

### ISSUE THREAD

**Issue by ruzannakamalyan** [assimp/assimp#921] opened 2016-06-21 07:38 UTC
Hi,
one of my fbx files has got a weird issue with displaying some meshes. It is missing some meshes( objects). However in other suitable applications the fbx gets displayed fully. Even in the Unity editor (I'm integrating assimp within a Unity application) the dropped in file is as it is, but after processing with assimp it misses some objects. Even more, some of the objects are stacked at the same position, far from the real parent.

Any help on this is highly appreciated!

p.s. Opened the model with **Open 3D Model Viewer**. The same problem is here.

**Comment by kimkulling** [comment] 2018-12-08 21:08
Maybe removed by the post-processing. Just check the logs for more information what was removed. I am really sorry that I haven't seen your question for 2 years. 
I will close the issue, just reopen it if the issue is still there.

**Closed by kimkulling** 2018-12-08 21:08 UTC
Labels: question
