### ISSUE TITLE
Collada export: no skinning

### ISSUE THREAD

**Issue by bmpix** [assimp/assimp#606] opened 2015-07-08 18:32 UTC
Hi, I'm trying to load a COLLADA scene with a skinned character and export it back. Everything is loaded correctly, but when I'm exporting, the skinning is lost and the skeleton is exported incorrectly.

To be more precise, I'm doing the following:

``` c++
Assimp::Importer importer;
const aiScene* scene = importer.ReadFile(import_filename,
        aiProcess_CalcTangentSpace |
        aiProcess_Triangulate |
        aiProcess_JoinIdenticalVertices |
        aiProcess_SortByPType);
Assimp::Exporter exporter;
exporter.Export(scene, "collada", export_filename);
```

The exported file doesn't have skinning section (`<library_controllers>` section is missing altogether) and joints are exported as simple groups (they don't have `type="JOINT"`). There might be some other errors, I wouldn't know. Am I missing something or it's a bug?

**Comment by wise86-android** [comment] 2015-07-13 12:26
Hi, no it's not a bug, it is a missing feature..
I'm trying to implement it, but it is work in progress, and this week I will not have time to work on it..

If you want I'm workning in this branch: https://github.com/wise86-android/assimp/tree/colladaExportBones

**Comment by bmpix** [comment] 2015-07-13 17:39
Thank you.

**Comment by acgessler** [comment] 2015-07-13 19:35
@wise86-android looking forward to the PR!

**Comment by kimkulling** [comment] 2020-01-28 18:23
Shall be fixed now.

**Closed by kimkulling** 2020-01-28 18:23 UTC
Labels: Bug
