### ISSUE TITLE
IFC-STEP: Update clipper library.

### ISSUE THREAD

**Issue by fire** [assimp/assimp#2401] opened 2019-04-03 16:26 UTC
In godot engine, using the IFC-STEP importer conflicts with the existing clipper library because one is from 2012 and the one in godot is more recent.

Godot uses:  6.4.2

Assimp uses: 4.8.8

**Comment by kimkulling** [comment] 2019-04-05 06:55
Currently I am working for my company on a Step-File importer. When doing this I plan to move the hole-mesher, which is using the clipper lib out of the IFC-importer. When doing this, I will update the clipper lib. 

I already tried to update the  clipper lib, but their changed the interface. So this task is not so easy when doing it at the evening :-).

**Comment by fire** [comment] 2019-04-05 13:51
Having CATIA support through assimp and step format would be amazing.

**Comment by Cgettys** [comment] 2019-04-10 12:38
This appears to be a duplicate of #788 , so whenever this get closed out, that probably can be to. Not saying that there's anything wrong with bringing it up, just pointing out that we can kill two issues at once here ;)

**Comment by ponahoum** [comment] 2019-06-27 20:57
Any news about this issue @kimkulling ? I can't import STEP file exported with SolidWorks/Catia, it's a standard in the industry, hope it will be fixed soon ! :)

**Comment by kimkulling** [comment] 2022-03-10 14:20
Duplicate to https://github.com/assimp/assimp/issues/788

**Closed by kimkulling** 2022-03-10 14:20 UTC
Labels: Bug
