### ISSUE TITLE
Please upgrade the contrib/zip dependency

### ISSUE THREAD

**Issue by dangelog** [assimp/assimp#3831] opened 2021-04-28 07:17 UTC
Hello,

We've received reports that the zip dependency in contrib/zip (which itself is a clone of https://github.com/kuba--/zip/) ships with a link to codecov in some .yml file. 

This is in the latest assimp master:
https://github.com/assimp/assimp/blob/74577ae3c79132b2d643ae667a1bd71e0a99f48f/contrib/zip/.travis.yml

These links trigger automatic code scanning tools, as codecov's bash has been recently compromised; you can read more about it here https://about.codecov.io/security-update/ . Although that shouldn't affect any assimp user (as users won't use the yml files in question), this compromises the ability of shipping assimp.

Upstream zip has already removed the links to codecov, for instance here: https://github.com/kuba--/zip/pull/118

So, I'd kindly like to ask to pull from upstream in order to get rid of that link from assimp's own sources, and make sure that all references to codecov are dropped in the next assimp's .zip release. Thank you!

**Comment by krishty** [comment] 2021-04-28 07:20
duplicate of https://github.com/assimp/assimp/issues/3792

**Comment by kimkulling** [comment] 2021-04-30 11:08
I am fighting with it. Minizip seems to have issues with the update.

**Comment by kimkulling** [comment] 2021-04-30 11:08
Thanks for the hint!

**Comment by kimkulling** [comment] 2021-04-30 16:01
Done!

**Closed** 2021-04-30 16:00 UTC
Labels: API, Bug

**Comment by dangelog** [comment] 2021-05-01 08:46
Thank you! I guess #3792 can be closed as well (apologies, didn't see there was a duplicate).
