### ISSUE TITLE
GLTF 2 is crashing on Android compilation

### ISSUE THREAD

**Issue by rickomax** [assimp/assimp#1472] opened 2017-10-04 21:56 UTC

**Comment by dhritzkiv** [comment] 2017-10-17 14:49
Duplicate of #1473 ?

**Comment by kimkulling** [comment] 2017-10-19 14:00
Good question.

**Comment by rickomax** [comment] 2017-10-24 23:29
Probably a duplicate.

**Comment by kimkulling** [comment] 2018-01-15 21:01
Ok, I will close it.

**Closed by kimkulling** 2018-01-15 21:01 UTC
Labels: bug
