### ISSUE TITLE
m3d.h redefines stb image functions. 

### ISSUE THREAD

**Issue by concubicycle** [assimp/assimp#2753] opened 2019-11-06 03:27 UTC
Around like 1022 of m3d.h, the file checks for the stb image header gurad and defines some stb image functions. This breaks my build. Shouldn't it be checking for the STB_IMAGE_IMPLEMENTATION define? 

In general, sticking stb functions into an h file like that without doing whatever preprocessor plumbing that stb does seems like a bad idea.

**Comment by quantumsheep** [comment] 2019-11-08 21:40
Same issue! If M3D requires implementations from `stb_image.h`, maybe including the whole header or whole `stb` project in assimp would a better solution.

`stb_image.h` doesn't have a specific pre-processor to tell if the PNG compressor is already implemented so we can't fix it that way.

**Comment by bztsrc** [comment] 2019-11-18 15:09
Could you please copy the exact error message? It works for me.

m3d.h does not require stb_image.h, and it does check for the STBI_INCLUDE_STB_IMAGE_H define, meaning if you include stb_image.h it won't. Checking for the STB_IMAGE_IMPLEMENTATION define would result in incorrect behavior, that's why it checks for the include's define.

Just for the records, this file format uses the same compression as PNG, therefore it needs a few functions also used for PNG, and it needs those without stb_image.h.

**Comment by bztsrc** [comment] 2019-11-18 15:17
I was wondering, when and how do you get these errors.

Assimp compiles without a problem as it does not include stb_image.h, and your code (which includes stb_image.h) should be _linked_ with libassimp, but in linking C header files does not play at all. So how exactly can a shared/dynamic library have a conflict with a header file?

Are you trying to compile some patched and modified version of Assimp inlined directly in your project? If so, simply include stb_image.h _before_ the Assimp headers, and the ifdef guards will take care of the rest.

**Comment by quantumsheep** [comment] 2019-11-18 16:13
I'm building and linking assimp with CMake. Building's done like that:
```cmake
set(ASSIMP_BUILD_NO_EXPORT ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
add_subdirectory(assimp)
```
and `stb_image` by including it in the `target_include_directories` directive.
```cmake
target_include_directories(${PROJECT_NAME} PUBLIC
    "${CMAKE_CURRENT_SOURCE_DIR}/include"
    "${CMAKE_CURRENT_SOURCE_DIR}/stb"
)
```

All the sources from `assimp` and `stb` are not modified.

**Comment by bztsrc** [comment] 2019-11-18 16:14
So you are not linking with the shared library? Instead you're compiling Assimp and stb_image directly into your code?

**Comment by bztsrc** [comment] 2019-11-18 16:40
Please copy paste the exact error message. You have a pre-compiler issue, and you're showing Cmake configs, which is unrelated.

I'm certain that the problem is in your build. If you don't want to dynamically link with Assimp, then the correct way is to compile a static library of Assimp and link your project with that. It looks like you're directly embedding the Assimp source, which is not how it should be done; but even that works if you include stb_image first (so that the pre-compiler knows it's included, and by the time Assimp source is compiled it has the pre-compiler define for the ifdef guard).

I really want to help you, but I need the exact error message.

**Comment by concubicycle** [comment] 2019-11-18 19:02
I was using assimp via ExternalProject_Add like:
```
ExternalProject_Add(assimp
    PREFIX assimp
    GIT_REPOSITORY https://github.com/assimp/assimp.git
    GIT_TAG master
	GIT_SHALLOW TRUE
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}/assimp
        -DBUILD_SHARED_LIBS=OFF
        -DASSIMP_BUILD_TESTS=OFF
        -DOpenGL_GL_PREFERENCE=GLVND
        -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
        -DASSIMP_BUILD_ZLIB=ON
        -DASSIMP_NO_EXPORT=ON
        -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
        -DASSIMP_BUILD_GLTF_IMPORTER=TRUE
        -DASSIMP_BUILD_OGRE_IMPORTER=TRUE # Contains common Animation namespace
)


set(ASSIMP_INCLUDE ${EXTERNAL_INSTALL_LOCATION}/assimp/include)



if(WIN32 AND MSVC)
set(ASSIMP_LIB 
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/assimp-vc${MSVC_TOOLSET_VERSION}-mtd${CMAKE_STATIC_LIBRARY_SUFFIX} # not sure how these names are generated....   
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/IrrXMLd${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/zlibstaticd${CMAKE_STATIC_LIBRARY_SUFFIX})
else()
set(ASSIMP_LIB 
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/libassimp${CMAKE_STATIC_LIBRARY_SUFFIX}    
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/libIrrXML${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/libzlibstatic${CMAKE_STATIC_LIBRARY_SUFFIX})
endif()
```

The args to exclude importers fix the issue with the m3d import - I added them later. When I comment them out and rebuild, I get:

```
/usr/bin/ld: ../external/assimp/lib/libassimp.a(M3DImporter.cpp.o): in function `stbi_zlib_decode_malloc_guesssize_headerflag':
/home/sava/digipen/cs529/RunShoot-clion/build/assimp/src/assimp/code/M3D/m3d.h:1022: multiple definition of `stbi_zlib_decode_malloc_guesssize_headerflag'; src/libasset.a(texture_manager.cpp.o):/home/sava/digipen/cs529/RunShoot-clion/thirdparty/opengllib/include/stb_image.h:4267: first defined here
/usr/bin/ld: ../external/assimp/lib/libassimp.a(M3DImporter.cpp.o): in function `stbi_set_unpremultiply_on_load':
/home/sava/digipen/cs529/RunShoot-clion/build/assimp/src/assimp/code/M3D/m3d.h:1416: multiple definition of `stbi_set_unpremultiply_on_load'; src/libasset.a(texture_manager.cpp.o):/home/sava/digipen/cs529/RunShoot-clion/thirdparty/opengllib/include/stb_image.h:4744: first defined here
/usr/bin/ld: ../external/assimp/lib/libassimp.a(M3DImporter.cpp.o): in function `stbi_convert_iphone_png_to_rgb':
/home/sava/digipen/cs529/RunShoot-clion/build/assimp/src/assimp/code/M3D/m3d.h:1421: multiple definition of `stbi_convert_iphone_png_to_rgb'; src/libasset.a(texture_manager.cpp.o):/home/sava/digipen/cs529/RunShoot-clion/thirdparty/opengllib/include/stb_image.h:4749: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/RunShoot.dir/build.make:204: RunShoot] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: CMakeFiles/RunShoot.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

**Comment by bztsrc** [comment] 2019-11-18 23:47
Hi,

Thanks! The problem is you try to link two static libraries, both having the same functions, because you haven't told M3D you're going to include your own version of stb_image. You should include stb_image.h in Assimp to let the compiler know, you're providing stbi_zlib in another object (just include stb_image.h, don't define anything, as that goes to texture_manager.cpp only). Just a sidenote, in this case it wouldn't help if m3d.h were checking for STB_IMAGE_IMPLAMENTATION, because neither that, nor the STBI_INCLUDE_STB_IMAGE_H is defined in your setup.

As a workaround, I've prefixed the functions, now it is awaiting in pull request. You can try that version if you download the latest https://github.com/bztsrc/assimp/blob/master/code/M3D/m3d.h (nothing else should be changed, just update this one file). Without including stb_image.h before m3d.h (which is the preferred way to tell M3D do not use the built-in stbi_zlib) your libassimp.a will be 13,206,856 bytes instead of 13,186,532 bytes (bigger by 20324 bytes), but that's all, there'll be no conflict any more.

(Just an interesting fact, Assimp also has it's own zlib compression implementation too, regardless if you link your project with zlib or not. Unfortunately that lib does not support sliding window for deflate, that's why stbi_zlib is needed.)

Cheers,
bzt

**Comment by concubicycle** [comment] 2019-11-19 01:19
Ah, thank you for the reply! I'll try this out some time.

**Comment by kwangsing3** [comment] 2019-11-20 13:29
Hi, I got similar error here, if I had my own stb_image.h, compiler would said some functions are already defined.
After changing m3d.h up there. Compiler said `_m3d_addvrtx`  `_m3d_addtmap`  `_m3d_addnorm` not defined.  or I got some misunderstanding?

I'm trying to do  `add_subdirectory(assimp) directly `  (using cmake), because I want to build it dynamically beetween different platforms,  even it's not recommended :P 
(Is there an official tutorial to teach how to include assimp from source code? not pre-build)

And, I found the similar issue here, what you think?

**Comment by bztsrc** [comment] 2019-11-20 15:06
Hi @kwangsing3, you're missing the entire patch. You have updated the SDK but not the wrapper class. I said to update the m3d.h for those who have already applied the patch; but now it's an outdated advice because in the meantime I've added it to the pull request as well.

Once this pull request gets merged, all these problems will go away, as all of this have been fixed. Please be patient.

**Comment by bztsrc** [comment] 2019-11-20 15:09
Alternatively I suggest to link your project with the dynamic library as it supposed to be.

Tutorial:
1. install the pre-built assimp library on your machine (.dll, .so)
2. add "-lassimp" to your linker.

**Comment by bztsrc** [comment] 2019-11-24 01:29
The pull request has been merged. Does the linking problem still exists, or is it resolved?

Cheers,
bzt

**Comment by kimkulling** [comment] 2019-11-27 16:27
PLease reopen this one if the issue still exists. 

Thanks a lot!

**Closed by kimkulling** 2019-11-27 16:27 UTC
Labels: bug, build
