### ISSUE TITLE
ASCII STL exporter produces invalid ASCII STL files.

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3756] opened 2021-04-12 21:44 UTC
Version 5.0.1, MSVC 2019, 64-bit Release build.

The ASCII STL exporter (id "stl") produces invalid ASCII STL files. 

The precise issue is that the exporter forgets to put a space between `endsolid` and the solid name at the end of the file. For example, it might produce a file like this, which is invalid:

    solid AssimpScene
        ...
    endsolidAssimpScene

When it should be producing a file like this:

    solid AssimpScene
        ...
    endsolid AssimpScene

Most ASCII STL parsers are pretty loose and don't care about `endsolid`, but some (notably the built-in Windows 10 3D model viewer) are more strict will fail to load the file.

The fix should be straightforward: Add a space between `endsolid` and the object name.

According to all sources that I know of, a space is required after `endsolid`. See the citations at https://www.loc.gov/preservation/digital/formats/fdd/fdd000506.shtml for examples.

**Comment by JC3** [comment] 2021-04-12 22:03
Example:

```
int main () {

    aiMesh *mesh = new aiMesh();
    mesh->mNumVertices = 3;
    mesh->mVertices = new aiVector3D [] {{0,0,0}, {0,1,0}, {1,0,0}};
    mesh->mNumFaces = 1;
    mesh->mFaces = new aiFace[1];
    mesh->mFaces[0].mNumIndices = 3;
    mesh->mFaces[0].mIndices = new unsigned[] { 0, 1, 2 };

    std::unique_ptr<aiScene> scene(new aiScene());
    scene->mNumMeshes = 1;
    scene->mMeshes = new aiMesh * [] { mesh };
    scene->mNumMaterials = 1;
    scene->mMaterials = new aiMaterial * [] { new aiMaterial() };
    scene->mRootNode = new aiNode();
    scene->mRootNode->mNumMeshes = 1;
    scene->mRootNode->mMeshes = new unsigned [] { 0 };

    Assimp::Exporter().Export(scene.get(), "stl", "corrupt.stl");

}
```

Produces the following file:

```
solid AssimpScene
 facet normal 0 0 -1
  outer loop
  vertex 0 0 0
  vertex 0 1 0
  vertex 1 0 0
  endloop
 endfacet

endsolidAssimpScene
```

Note the weird ending.

**Comment by kimkulling** [comment] 2021-04-13 07:59
Hi,
thanks a lot for the bug report. The good news are that the issue is already fixed on the current master (check https://github.com/assimp/assimp/commit/8ba1d38deac09228aa58589f2a09e64a80584f16#diff-9060a4dd8be308e43a38f9764e31900c3dbbca1d59c56ea265d9e679a41bd57d)

Kim

**Closed** 2021-04-13 07:59 UTC
