### ISSUE TITLE
Memory Leak in Importer

### ISSUE THREAD

**Issue by ChuanChinLai** [assimp/assimp#2082] opened 2018-08-04 18:34 UTC
Hi 

Recently I use Assimp to import my model in OpenGL project. 
However, it has a memory leak in the .obj importer code. I have no idea why this happens.  

int main()
{
        int abc = 0;

	Assimp::Importer imp; // if comment this then no memory leak...

#if defined _DEBUG
	_CrtDumpMemoryLeaks();
#endif // _DEBUG

        return 0;
}

Detected memory leaks!
Dumping objects ->
{713} normal block at 0x000002140AF0F320, 16 bytes long.
 Data: <                > 00 8C F0 0A 14 02 00 00 00 00 00 00 00 00 00 00 
{712} normal block at 0x000002140AF001D0, 48 bytes long.
 Data: <                > D0 01 F0 0A 14 02 00 00 D0 01 F0 0A 14 02 00 00 
{711} normal block at 0x000002140AF08C00, 24 bytes long.
 Data: <                > 20 F3 F0 0A 14 02 00 00 D0 01 F0 0A 14 02 00 00 
{710} normal block at 0x000002140AF08FC0, 32 bytes long.
 Data: <                > 98 05 C4 0C F9 7F 00 00 00 8C F0 0A 14 02 00 00 
{709} normal block at 0x000002140AF090E0, 32 bytes long.
 Data: < P              > A0 50 C1 0C F9 7F 00 00 00 8C F0 0A 14 02 00 00 
{708} normal block at 0x000002140AF11790, 296 bytes long.
etc...

Windows 10, visual studio 2017 and Assimp 4.1.0

**Comment by kimkulling** [comment] 2018-08-07 17:36
Thanks for the report. I will check that.

**Comment by kimkulling** [comment] 2018-08-08 10:27
I can reproduce the issue, stay tuned.

**Comment by kimkulling** [comment] 2018-08-08 19:47
You will get all the allocations inside classes which are stored on the stack as memory-leaks because they are not released when checking for leaks. The cleanup for the stack will be done after leaving your main-function.
OFr instance Importer does allocate a private instance of shared data, which will be released when leaving main and the stack get cleaned up. But your check will detectd this as a leak, even if it will be released correctly. 

That is the reason that of CI-chain ist checking for global leaks. Thanks a lot for the hint, I have a much better understanding now!

**Closed by kimkulling** 2018-08-08 19:47 UTC
Labels: Question, Leak
