### ISSUE TITLE
Failed to build Assimp by CMake and the latest version of MinGW

### ISSUE THREAD

**Issue by RainSureZhao** [assimp/assimp#5196] opened 2023-08-06 08:47 UTC
**Describe the bug**
Bug: Failed to build Assimp by CMake and the latest version of MinGW.

**To Reproduce**
1. Download the 5.2.5 version to the specified directory.
2. Edit CMakeLists.txt as follow: 
```txt
if (NOT TARGET assimp)
    set(ASSIMP_WARNINGS_AS_ERRORS OFF)
    add_subdirectory(assimp)
    set_target_properties(assimp PROPERTIES FOLDER ${third_party_dir}/assimp)
endif()
```
3. Build project.
4. See error: [error: possibly dangling reference to a temporary]

**Expected behavior**
Build the project correctly and generate the executable.

**Screenshots**
![image](https://github.com/assimp/assimp/assets/73586413/86bb3c50-01d9-4849-8fb2-74be3ee789db)

![image](https://github.com/assimp/assimp/assets/73586413/948cb88b-fdfe-42c0-b0da-21b8e45ad572)

**Platform (please complete the following information):**
 - OS: Windows 10
 - CMake: 3.25.1
 - gcc version 13.1.0 (x86_64-posix-seh-rev1, Built by MinGW-Builds project)
 - MinGW-w64: [x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1.7z](https://github.com/niXman/mingw-builds-binaries/releases/download/13.1.0-rt_v11-rev1/x86_64-13.1.0-release-win32-seh-ucrt-rt_v11-rev1.7z)

**Additional context**
None.

**Comment by turol** [comment] 2023-08-07 11:05
Duplicate of https://github.com/assimp/assimp/issues/5145

https://github.com/assimp/assimp/pull/5163/ fixed it but not for mingw for some reason.

**Comment by turol** [comment] 2023-08-07 11:05
@thegeeko Please augment your fix to also fix mingw

**Closed** 2023-08-07 11:15 UTC
Labels: Bug
