### ISSUE TITLE
Wrong assumption in comment

### ISSUE THREAD

**Issue by reduz** [assimp/assimp#2596] opened 2019-08-15 18:31 UTC
https://github.com/assimp/assimp/blob/a4907e54b11007e517c1532e81b47f21f09ad59f/code/PostProcessing/JoinVerticesProcess.cpp#L436

I used to assume this and did a similar optimization in Godot, until I had to work on a paper folding game, where things had a shape and then changed into another shape (kind of like paper transformers). Had to remove the optimization.

**Comment by kkulling** [comment] 2019-08-16 06:32
Right, this comment comes from a different time far far ago. I will overwork it. 

Thanks for the hint!

**Comment by fire** [comment] 2019-08-19 05:47
For posterity, the causes the bone 5 to disappear in https://github.com/assimp/assimp-mdb/blob/master/model-db/fbx/huesitos.fbx.

**Comment by RevoluPowered** [comment] 2019-08-19 18:14
**Broken example**
![broken](https://user-images.githubusercontent.com/748770/63288793-7dfb4880-c2b5-11e9-9df3-9eaa0793fee2.png)

*Bone removal code disabled example*
![working](https://user-images.githubusercontent.com/748770/63288815-881d4700-c2b5-11e9-8927-1bfc2461e31f.png)

**Comment by RevoluPowered** [comment] 2019-08-19 18:15
@kimkulling do you mind if I PR with this code removed?

**Comment by kimkulling** [comment] 2019-08-26 20:08
Thanks for the pull request, I will close this one.

**Closed by kimkulling** 2019-08-26 20:08 UTC
Labels: Doc, bug
