### ISSUE TITLE
FBX imports always have animation duration of 0

### ISSUE THREAD

**Issue by domhofmann** [assimp/assimp#1175] opened 2017-02-10 23:04 UTC
I'm trying to import two different FBX files with bones + animation. Bones seem to load okay but animations only seem to load the first frame and report a duration of 0. Both files import properly in other tools I've tried (FBX Review, Cinema 4D, Unity).

See the attached files:
[fbx_examples.zip](https://github.com/assimp/assimp/files/767982/fbx_examples.zip)

**Comment by domhofmann** [comment] 2017-02-11 00:18
Strangely, the animations do appear to import properly if I go back to Assimp 3.1.1.

**Comment by kimkulling** [comment] 2017-03-01 08:49
So I have introduced a bug. Fuxxx ...

Thanks for the report!

**Comment by domhofmann** [comment] 2017-03-06 17:12
It happens. :) I'll see if I can find anything as well.

**Comment by prk223** [comment] 2017-05-15 01:05
I'm having the same problem with a different FBX file I'm using.
Appears to have been caused by commit 08ba782bd5fd1d0392b70e675db99702ff349b7f. Specifically, you can just roll back FBXConverter.cpp to the version before to make the problem ago away (might also have to manually remove boost and update includes to get it to build with the rest of 3.3.1).
The FBX file that was added during that commit works for me. My guess is that my FBX does not have the LocalStart/LocalStop populated which is needed by that commit's changes. Anybody know if there's something I can run on FBX files to make them support those attributes?

**Comment by rickomax** [comment] 2017-08-03 15:22
Got a file with this issue too. Gonna take a look at the source to try fixing soon.

**Comment by GUNDAM92** [comment] 2017-08-17 03:17
4.0.0,4.0.1,3.3.1and3.1.1.Only 3.1.1 is true。

**Comment by kimkulling** [comment] 2017-08-25 14:10
Closed by  ce9c8a4 i

**Closed by kimkulling** 2017-08-25 14:10 UTC
