### ISSUE TITLE
FBX import scene hierarchy is broken by unnamed nodes

### ISSUE THREAD

**Issue by jonaskivi** [assimp/assimp#1908] opened 2018-04-23 06:47 UTC
I briefly tested the commit 6a0dc071a967be9d69ed86228f21be04dfec23d6 cloned on April 9th 2018, and had many problems with FBX import and hierarchies. These problems are not present in the latest release 4.1.0.

I was importing mostly FBX files, and it seems that with deeper hierarchies Assimp would insert unnamed parent nodes containing the transform of their child, and then their child node would have the node name (as written in 3DS Max or Maya).

This was especially visible with animations where each bone would have an unnamed parent (containing the transform). But it also happens on files which don't have animations.

So for most deep nodes we get this:
> The usual $AssimpFbx$_PreRotation etc. nodes
> Some parent which has a proper name and transform
>----unnamed parent node with transform
>-------- its child node, which has the node name, but identity transform

I'm not sure if this is some new feature, or just broken stuff in master, but it would be nice to know if this can be fixed, or if not, the reasons for the change.

If this is a bug, I would expect the hierarchy to roughly match the hierarchy that was set in 3DSMax or Maya, and not contain those unnamed parent nodes, like it does in Assimp 4.1.0.

**Comment by mesilliac** [comment] 2018-05-24 15:18
I can't reproduce this, i don't have any unnamed nodes in my heirarchy for any of my test fbx files. Do you have a simple FBX file exibiting this behaviour that we could use for testing?

There were some changes recently to better support 3DS Max transform behaviour, but none of them should be adding unnamed nodes.

**Comment by mesilliac** [comment] 2018-05-25 10:13
scratch that - actually i can reproduce, it seems to have been introduced sometime after my changes. Not sure what's up, but i'm seeing these uamed nodes as well.

**Comment by ObsydBT** [comment] 2018-05-25 10:27
Same here! I can see unnamed nodes in Assimp Version: 4.1.230369876.

**Comment by kkulling** [comment] 2018-05-25 19:32
Hi,

not to worry, shit happens sometimes. @mesilliac could you please prepare some kind of fix for that issue?

**Comment by ObsydBT** [comment] 2018-07-26 10:56
Any news regarding this issue?

**Comment by kkulling** [comment] 2018-07-26 11:15
As far as I know this issue is fixed on the current master.

**Closed** 2018-07-26 11:16 UTC

**Comment by ObsydBT** [comment] 2018-07-27 10:14
I'm on version 4.1.59846594. As soon as I get the latest version I will test and report back.

**Comment by ObsydBT** [comment] 2018-07-28 07:14
Tested with the latest version! The unnamed nodes are gone! Thank you!

**Comment by sanonz** [comment] 2019-05-30 04:33
> Tested with the latest version! The unnamed nodes are gone! Thank you!

What version did you use when it's working good?
