### ISSUE TITLE
Unable to load STEP-Files

### ISSUE THREAD

**Issue by LarsSluijter** [assimp/assimp#2000] opened 2018-06-06 09:52 UTC
Hello there,

I'm trying to convert a STEP (.stp, ISO-10303-21) file to COLLADA (.dae) file.
The readme states STP files are supported, however I get the following error when I try to convert it:
`ERROR: Failed to load file: IFC: Unrecognized file schema: AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }`

Is there any solution to this problem?

**Comment by Rayfoundry** [comment] 2018-06-16 14:34
I think the issue is that Assimp only support IFC files which are based on Step but only syntactically. It would probably be a good idea to update the documentation on this. Also for Step support, pythonocc https://github.com/tpaviot/pythonocc-core could be used. It's based on OpenCascade (a CAD kernel) and allows meshing to STL at least.

**Comment by kimkulling** [comment] 2018-08-22 11:58
Any open spec?

**Comment by kimkulling** [comment] 2018-08-26 19:09
Just started ...

**Comment by doug-matthews** [comment] 2018-09-06 00:35
I've found this website to be a good resource anytime I've had to work with step files. They have some descriptions about the formats and some examples of step files from different platforms:
[https://www.cax-if.org/library/](https://www.cax-if.org/library/)

**Comment by kimkulling** [comment] 2018-10-06 08:45
Started to work on it.

**Comment by Frinalal** [comment] 2018-10-17 10:55
I'm getting a few warnings realted to STEP and IFC when building. [Output log](https://pastebin.com/y0RQBV2j)
Using `importer.ReadFile(filename, aiProcessPreset_TargetRealtime_MaxQuality)` returns _Validation failed: A node of the scenegraph is NULL_ when reading a ISO-10303-21 .stp file.

**Comment by jsdtaylor** [comment] 2019-04-16 07:52
Hey @kimkulling. Is this in a roadmap to be fixed? I'd *love* to use this. :)

**Comment by ponahoum** [comment] 2019-06-20 22:37
Any news about this issue? Trying to open step files from Autodesk Inventor and it gives me the same error. Is it fixed by the RC5 by any chance ?

**Comment by johannnovak** [comment] 2020-12-03 21:49
Hey @kimkulling. I encountered the same issue with the NULL node in the scenegraph. No luck in finding any solutions to fix this issue ?

**Comment by Frinalal** [comment] 2020-12-04 08:40
@johannnovak A couple of isssues related to STEP / STP are in the [ToDo list for release 5.1](https://github.com/assimp/assimp/projects/4), so hopefully some work gets done soon. See #2945 #2401 #2734

**Comment by johannnovak** [comment] 2020-12-04 08:43
Hi @Frinalal,
Okay thanks for the info and the links. I'll check these out !

**Closed** 2021-12-16 19:59 UTC
Labels: Feature-Request

**Comment by visusys** [comment] 2022-03-01 18:10
Is there any update on this? Still getting `ERROR: Failed to load file: IFC: Unrecognized file schema: AUTOMOTIVE_DESIGN` when trying to convert a step file to OBJ/FBX. Are there any other CLI tools that will accomplish this?

**Comment by tellypresence** [comment] 2025-04-16 16:06
#2878 has better title, using that for tracking
