### ISSUE TITLE
Cannot import x files in DirectX 9.0c, which were generated with assimp (open3mod)

### ISSUE THREAD

**Issue by CowNChicken** [assimp/assimp#1308] opened 2017-06-13 07:49 UTC
Hello,

I cannot import x files in DirectX 9.0c, which were generated with assimp (open3mod).
To make sure, the tiger.x and some other y files worked, only the assimp x files fail. 

Another issue is, that the export crashes in several cases, for ex. when the textures of an obj file were not loaded correctly and if the checkbox "include scene hierarchy" is checked even open3mod cannot load the successfully exported x files. 

We would donate it, if that issues will be fixed till September.

Many greetings,
Cow

**Comment by kimkulling** [comment] 2017-06-13 12:22
Hi,

have you used the samer version? And could you provide a small model, which shows the problem please?

Thanks,
Kim

**Comment by CowNChicken** [comment] 2017-06-14 10:41
Hello Kim,

thank you for your reply.. oder soll ich danke sagen? ;)
I’ve made an error video, that show you, what I told about.
Can I send it via email? 

LG,
Cow

**Comment by kimkulling** [comment] 2017-06-14 11:09
Klar! :-) Sure!

CowNChicken <notifications@github.com> schrieb am Mi., 14. Juni 2017 um
12:41 Uhr:

**Comment by CowNChicken** [comment] 2017-06-14 11:14
Wie denn?

Von: Kim Kulling [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. Juni 2017 13:10
An: assimp/assimp
Cc: Angelo Hoenicke; Author
Betreff: Re: [assimp/assimp] Cannot import x files in DirectX 9.0c, which were generated with assimp (open3mod) (#1308)

Klar! :-) Sure!

CowNChicken <notifications@github.com<mailto:notifications@github.com>> schrieb am Mi., 14. Juni 2017 um
12:41 Uhr:

**Comment by CowNChicken** [comment] 2017-06-14 11:28
Hey,

hierüber geht’s nicht. Email kann wegen der Anhänge (allerdings nur 7 MB) nicht versendet werden.


Von: Kim Kulling [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. Juni 2017 13:10
An: assimp/assimp
Cc: Angelo Hoenicke; Author
Betreff: Re: [assimp/assimp] Cannot import x files in DirectX 9.0c, which were generated with assimp (open3mod) (#1308)

Klar! :-) Sure!

CowNChicken <notifications@github.com<mailto:notifications@github.com>> schrieb am Mi., 14. Juni 2017 um
12:41 Uhr:

**Comment by kimkulling** [comment] 2017-06-14 11:48
Upload via hoster for instance?

**Comment by CowNChicken** [comment] 2017-06-14 12:03
https://drive.google.com/drive/folders/0B3ZYGlHp0vr7enp0d0w1WGpJb1E?usp=sharing

Von: Kim Kulling [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. Juni 2017 13:49
An: assimp/assimp
Cc: Angelo Hoenicke; Author
Betreff: Re: [assimp/assimp] Cannot import x files in DirectX 9.0c, which were generated with assimp (open3mod) (#1308)


Upload via hoster for instance?

**Comment by CowNChicken** [comment] 2017-06-14 12:07
Fuck everybody sees that here.. I replied via mail!!

**Comment by kimkulling** [comment] 2017-06-14 12:11
You can send me the link via mail :-)

**Comment by CowNChicken** [comment] 2017-06-14 12:18
To which adress? I am new here. I find no adress at your profile and if I reply in outlook it lands here ;)
By the way the link you see 3 post above. I will delete it in 10 min.

**Comment by CowNChicken** [comment] 2017-06-14 12:35
Have you got the files?

**Comment by kimkulling** [comment] 2017-06-14 12:56
kim.kulling(at)googlemail.com

**Comment by kimkulling** [comment] 2017-06-14 22:18
Ok, got the modes, could you please describe how to reproduce the issues? The obj and 3ds import works.

Which exports failes? Thanks a  lot!

I guess solving this issues should be possible until september.

**Comment by kimkulling** [comment] 2017-06-16 07:01
I already took a look onto the x-export. This is broken, correct. I will do my very best!

**Comment by kimkulling** [comment] 2017-07-04 07:00
The x-import after exporting it failed because the X-Importer is not able to deal with lines. So an easy workaround will be to make the X-importer more tolerant.

**Comment by kimkulling** [comment] 2017-07-10 11:35
Fixed by 647b59b7fa84586c59a60bf03f4d6a1f701c6b2d . Please repoen if other bugs have occurred.

**Closed by kimkulling** 2017-07-10 11:35 UTC
