### ISSUE TITLE
Bug: Cannot convert blender and mdl files

### ISSUE THREAD

**Issue by root2185** [assimp/assimp#5208] opened 2023-08-16 11:24 UTC
**Describe the bug**
Cannot convert blender file to mdl or others.
Also converting a mdl generated from blender with https://gitlab.com/luckeyproductions/tools/DryBlend doesn't work.

**To Reproduce**
Try to convert:
```
assimp export untitled.blend untitled.ply
param = untitled.ply
assimp export: select file format: 'ply' (Stanford Polygon Library)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
0 %
50 %
ERROR: Failed to load file: Constructing BlenderDNA Structure encountered an error:
BlendDNA: Did not find a field named `no` in structure `MVert`

assimp export untitled.blend untitled.mdl
param = untitled.mdl
assimp export: no output format specified and I failed to guess it

assimp export Cube.041.mdl Cube.041.ply
param = Cube.041.ply
assimp export: select file format: 'ply' (Stanford Polygon Library)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
0 %
50 %
ERROR: Failed to load file: Unknown MDL subformat Cube.041.mdl. Magic word (UMDL) is not known
```

**Expected behavior**
To be able to convert.

**Platform (please complete the following information):**
 - Distro: Artix Linux
 - Version assimp: 5.2.5-2
 - Version blender: 3.6.0-4

**Comment by root2185** [comment] 2023-08-16 14:32
No.
```
assimp export untitled.blend untitled.mdl
param = untitled.mdl
assimp export: no output format specified and I failed to guess it

assimp export untitled.blend untitled.ply
param = untitled.ply
assimp export: select file format: 'ply' (Stanford Polygon Library)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
50 %ERROR: Failed to load file: Constructing BlenderDNA Structure encountered an error: 
Expected target to be of type `MLoop` but seemingly it is a `MPoly` instead

assimp export Cube.041.mdl Cube.041.ply
param = Cube.041.ply
assimp export: select file format: 'ply' (Stanford Polygon Library)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
50 %ERROR: Failed to load file: Unknown MDL subformat Cube.041.mdl. 
Magic word (UMDL) is not known

```

**Comment by turol** [comment] 2023-08-17 08:30
It gives a different error message. Maybe the Blender format has changed again.

**Comment by kimkulling** [comment] 2023-09-10 11:23
I guess this issue is caused by the latest blender formats. Currently, there is an open issue with the latest blender format. To workaround this you can just export the file as FBX and try to write this file.

There is already an open issue for the blender issue, so I will close this one as duplicated.

**Closed by kimkulling** 2023-09-10 11:23 UTC
Labels: Bug

**Comment by root2185** [comment] 2023-09-11 20:15
I exported from blender as FBX.

```
assimp export test.fbx test.mdl
param = test.mdl
assimp export: no output format specified and I failed to guess it

```
Is that the workaround?
It doesn't work here.

**Comment by stephengold** [comment] 2023-10-27 22:24
> There is already an open issue for the blender issue, so I will close this one as duplicated.

@kimkulling Which blender issue was this a duplicate of?
