### ISSUE TITLE
Segfault when loading some OBJ model

### ISSUE THREAD

**Issue by dankex** [assimp/assimp#714] opened 2015-12-14 03:32 UTC
OBJ package: http://www.mediafire.com/download/yobz1rdckzbxa18/Su-35_SuperFlanker.7z
Platform: Mac OS 10.10.3
Command line: ./assimp export Su-35_SuperFlanker.obj su.dae

assimp export: select file format: 'collada' (COLLADA - Digital Asset Exchange Schema)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
Segmentation fault: 11

**Comment by dankex** [comment] 2015-12-20 09:45
It crashes when loading the model alone.

**Comment by kimkulling** [comment] 2015-12-26 23:20
There was a null pointer access caused by an invalid texture type. The crash shall be fixed now. I am not so sure regarding the texture type.

**Comment by danke-sra** [comment] 2015-12-27 06:09
I have some handling for the texuture type. If the model loads with no problem, that's great! Thanks for the fix.

**Comment by kimkulling** [comment] 2015-12-27 19:38
OK, then I will close the issue.

**Closed by kimkulling** 2015-12-27 19:38 UTC
