### ISSUE TITLE
[5.2.3 Regression] Importing a FBX with animation show a twisted model

### ISSUE THREAD

**Issue by jianliang79** [assimp/assimp#4487] opened 2022-04-17 05:25 UTC
I have a FBX model with skeletal animation, importing it with Assimp 5.0.2 works fine. But with Assimp 5.2.3(and 5.1.6), the model is twisted when drawing it with the skeletal animation.
    You can download the FBX model file with the following link:
https://drive.google.com/file/d/1D7UqR0kkHZRxNDqVMgQCIncYQmnZd4_Y/view?usp=sharing

Screenshot with Assimp 5.0.2:   
![man-correct](https://user-images.githubusercontent.com/11371201/163701667-1b502859-7047-4ba2-97b2-295d2ff85910.jpg)

Screenshot with Assimp 5.2.3:
![man-wrong](https://user-images.githubusercontent.com/11371201/163701672-4658802c-eb50-4e3a-920c-697c76306315.jpg)

**Comment by dimitre** [comment] 2022-05-04 15:24
Happening here too. This model can be used to bissect where the issue was introduced.
https://github.com/openframeworks/openFrameworks/blob/master/examples/3d/assimpExample/bin/data/astroBoy_walk.dae

**Comment by dimitre** [comment] 2022-05-04 20:04
I've tested right now with 5.0.1 and it works great. 
Strangely assimp.a is approx 400mb and this release generates. 
Next tag I could build was 5.1.0, model is twisted already, 
assimp.a is much lighter , about 40mb and there is no libIrrXML.a.

**Comment by jinfagang** [comment] 2022-05-29 10:44
Does this solved? @dimitre your model on my side even directly coredumped when animate.

**Comment by cpope9141** [comment] 2022-06-15 16:25
Is this a duplicate of #3390?

**Comment by mwestphal** [comment] 2024-01-23 07:18
Any news on this one ? It is still present here.

**Comment by tellypresence** [comment] 2024-08-16 05:38
Unable to load model `hello.fbx` (reattached directly in case the share site linked [above](https://github.com/assimp/assimp/issues/4487#issue-1206285250) goes away in future), possible invalid meshes -- anyway crash-on-load in my implementation
[hello.fbx.zip](https://github.com/user-attachments/files/16633300/hello.fbx.zip)

**Comment by tellypresence** [comment] 2024-10-13 01:42
@jianliang79 Can you please post the textures for that model?  They don't seem to be in the .zip file you uploaded earlier -- thank you

**Closed** 2024-10-14 09:24 UTC
Labels: Bug

**Comment by dimitre** [comment] 2024-10-14 13:54
Almost all previous models working OK now, thank you.
I'm uploading this one which is not loading correctly
[TurbochiFromXSI.dae.zip](https://github.com/user-attachments/files/17364881/TurbochiFromXSI.dae.zip)

**Comment by tellypresence** [comment] 2024-10-14 17:52
@dimitre 
This issue has been closed.  Please raise a new issue for your .dae problems; it's just a coincidence they were also broken, nothing to do with fix to the FBX importer changes
