### ISSUE TITLE
307 warnings with MSVC14 (Visual Studio 2015) in x64 build

### ISSUE THREAD

**Issue by TamasSzep** [assimp/assimp#1065] opened 2016-11-13 17:45 UTC
Mostly coming from from sizeof(size_t) != sizeof(unsigned).

**Comment by kimkulling** [comment] 2016-11-14 19:18
Hm, we need to move to size_T I guess. Thanks for the report!

**Comment by TamasSzep** [comment] 2016-11-14 21:17
I would strongly discourage the usage of size_t overall. In fact, there are virtually no possible candidate that stores a size and needs more than 4 bytes. I like to follow the practice of using unsigned everywhere, and interacting with STL by casting it's size_t-s at the very first encounter:

auto countElements = static_cast<unsigned>(vector.size());
for(unsigned i = 0; i < countElements; i++) { /* */ }

It becomes important when storing a lot of indices, which is kind of the best practice of organizing your data, since it flattens your memory usage patterns, which makes your application efficient. As far as I known. : )))

**Comment by jaredmulconry** [comment] 2016-11-15 02:47
This seems like a question of design and intended use cases. Is Assimp intended to support meshes with more than 2^32 indices? Considering the presence of 'unsigned int' in all of the commonly used interfaces, I would guess not.
I think it doesn't make sense for Assimp to be using unsigned types in many of the places it is currently, since if any one of those overflows and wraps, I don't think good things would happen.
That said, it may not be practical to translate everything into signed types.

I'm interested in addressing the many build warnings that Assimp produces, so I'd be interested in discussing a way of approaching this in general, not just for MSVC.

**Comment by TamasSzep** [comment] 2016-11-15 08:48
Meshes with more than 2^32 indices, or even with more than a million indices are fairly impractical, one would split them for sure to enable more materials, separate culling, etc. But even if this should be supported, it's clear that sizes like the number of meshes, nodes, animations, materials will never be more than 2^32. So I would keep the current design and simply kill the warnings by casting to unsigned.
About signed vs. unsigned: signed becomes practical in implementations, where you want to iterate backwards. Since that is algorithmic question and has nothing to do with the libraries interface, I would keep the unsigned values since they express explicitly that you are dealing with sizes and indices. If somebody doesn't like it, he/she can cast it to signed anyway. : )))

**Comment by kimkulling** [comment] 2016-11-15 09:21
We had a discussion regarding this topic some years ago. For point of potability size_t is the right choise because this type was introduced to make size definitions better portable.
From the point of data we will not need this kind of type I guess. And it will be an API-change.

So from my point of view ( avoid too much trouble without getting a real benefit ) it would be ok for me to disable these warnings. It would be great if you could prepare a pull request for us!

**Comment by smalcom** [comment] 2016-11-15 10:19
> signed becomes 
signed for counting - its stupidest idea of "programmers". From modern libraries look at Qt. Do you count your food in refrigerator at negative axis? "Look honey, we have minus two cups of milk".

> Is Assimp intended to support meshes with more than 2^32 indices?
How many time ago meshes with 2^10 became rendered in real-time? But some formats did not support more than 2^32 objects. I also researched this trouble with warnings. I think its bad idea just change all, every importer and exporter need personal decision.

**Comment by TamasSzep** [comment] 2016-11-15 11:44
I would put:

#include <cassert>
#include <limits>
#include <type_traits>

template <typename T, typename = std::enable_if_t<std::is_integral<T>::value>>
inline T Cast(size_t value)
{
	assert(value <= static_cast<size_t>(std::numeric_limits<T>::max()));
	return static_cast<T>(value);
}

in types.h to the global namespace in the first #ifdef __cplusplus block. Now you can call this cast function, so you get rid of the warnings and even get notified at runtime when the cast goes wrong. Whenever you have time for actually revisiting all these decisions, you can simply search for "Cast<" and you will find all places that you have to revisit.

**Comment by smalcom** [comment] 2016-11-15 12:29
Thank you for assert at runtime. Low bow. Its best thing ever - crashing app using unhandled exceptions.
And second thank for runtime casting. Assimp too fast for regular people.

Look problem is simple. For example. You read mesh count and want to use it with size_t. Mesh count holded in uint32_t because - specification. So, you can simply use that at first time:
sizet_var = (size_t)mesh_count;
ans in constructor just use simple
static_assert(bla-bla sizeofs).

Its just example. Of course you can use uint32_t for all vars in importer when you need. But for 64bit CPUs using 64bit vars is better. So you can use uint32_t when required by format specs (do not forget source its not just machine language, but book for another developer) and use size_t for loops, intermediate calculation etc.
Thats what i think )

**Comment by smalcom** [comment] 2016-11-15 12:34
I dont say: "dont touch anything! A-a-a-a!". I mean (as said above): situation has no general decision, every place (warning) must be researched in context to it and fixed.

**Comment by TamasSzep** [comment] 2016-11-15 13:03
"Thank you for assert at runtime. Low bow. Its best thing ever - crashing app using unhandled exceptions."

It's WAY better to crash the application with a meaningful error message then silently messing up the data, and letting the user debug your code to find out that you missed to inform him/her about an invalid cast.

"And second thank for runtime casting. Assimp too fast for regular people."

Static cast - as it's name suggests - is static. It happens at compilation time, when the compiler instantiates the template function with a specific type. It doesn't make any sense to "runtime cast" integers.

"You read mesh count and want to use it with size_t. "

I think when you program storage things it's better to stick to explicitely sized types like uint32_t or uint64_t. Remember that these things eventually end up in the memory of your graphics device, you have to make sure that you know what sizes you are using.

Maybe one should name the function something else that expresses the assert in debug build (like CastWithAssert) but I think it's in fact a pretty good solution.

**Comment by smalcom** [comment] 2016-11-15 13:24
assert its a debug paradigm and realy ooooold paradigm. Application must no crash at all. Use return values, use throw/catch, use state machines. Anything but not a assert. Assert its mark of a "not good" developer.
Good static cast. But not good at all. Problem still here - developer just won't to read specs. Thats bad.

**Comment by smalcom** [comment] 2016-11-15 13:26
Can you show few places for discuss. Because at now we are still talking about what is better white color or black color but nothing is color (mix of EM-waves and nothing )))) )

**Comment by kimkulling** [comment] 2016-11-15 14:12
Please calm down! 

Normally something like:
unsigned int size = static_cast<unsigned int>( vector.size() );

should be enought. I don't thing using a template to avoid overflows will introduce so much benefits exepting irretations on my side :-).

**Comment by TamasSzep** [comment] 2016-11-15 14:30
I think you guys should figure out what you want. : ))) Maybe the bottom line is to create an x64 build (the problem is not MSVC related) and test the code for warnings before merging it.

**Comment by kimkulling** [comment] 2016-11-15 18:25
Just clear for me was I want: no compile errors and no API break!

**Comment by jaredmulconry** [comment] 2016-11-16 02:21
When I invited discussion of this topic, I didn't expect quite this flood of responses. :p

I'm certainly not in favor of breaking the world in trying to fix bugs. That being said, I believe I saw that a new major version of Assimp may be open to breaking API/ABI changes. So that may present an opportunity for us to come to some agreement on this larger issue.
As a minor addition to the signed/unsigned debate, I've already spotted at least one interface in the FBX Converter that deals in 'int', so at least one contributor to this project had this idea.

As for the warnings that are present currently, I'm happy to evaluate each case and perform the appropriate casts. If I encounter any specific cases that are unclear as to their intended behavior, I will raise them in the Assimp room on gitter.im, so I don't spam you all with github comment notifications.

I'll submit a pull request once I have them all addressed, or as my progress is deemed worthwhile to merge in.

**Comment by jaredmulconry** [comment] 2016-11-27 22:00
Pull request #1083 should address this issue for now.
I agree with @TamasSzep that a policy should be in place to prevent warnings of this nature from returning.

I recommend that any conversions from size_t to some other type, even to unsigned int, should be handled with a static_cast. This should prevent these warnings from surfacing again, as well as document points at which conversions are taking place intentionally.

I'll be following up on this issue in the future by submitting another pull request that deals with gcc and clang warnings.

**Comment by jaredmulconry** [comment] 2017-09-10 08:25
I've been away from this task for a while now. Compiling the project today in VS 2017 Win64 at /W3 gives me 30 warnings. 26 of these are conversion warnings, a majority of them are conversions from size_t.

Has there been any conclusion on how we should be handling this across the project?
I will be fixing these warnings again and I recommend this issue be closed afterwards. I will address remaining warnings in other compiler environments once I have them set up on my new home system.

**Comment by jaredmulconry** [comment] 2017-09-10 14:27
#1425 addresses this issue. I will file a separate issue for build warnings on other compilers.

**Comment by jaredmulconry** [comment] 2017-09-24 07:39
@kimkulling @TamasSzep I've built as much of the project as I can at head (I can't get qt set up correctly to build the qt-based viewer) and I've spotted no warnings in this config. I consider this issue closed.

**Comment by kimkulling** [comment] 2017-09-24 08:19
Closed by #1330

**Closed by kimkulling** 2017-09-24 08:19 UTC
