### ISSUE TITLE
Question/Explanation: Solving Linker Errors when Building with Premake

### ISSUE THREAD

**Issue by lucho1** [assimp/assimp#3970] opened 2021-06-27 22:03 UTC
Hi all!

I'm trying to implement the last release of assimp (5.0.1) in an engine I'm doing for personal purposes and I can't manage to link it properly, I'm having issues I don't know how to solve, and I guess it's caused from the way I'm including it. I tried to check on the documentation but I found nothing so I created this issue since it could be helpful (maybe?).

I'm working with Visual Studio 2019 in Windows in a C++ environment and I made the build with cmake following the instructions from the assimp documentation. In order to implement it in the project, I added the folders 'code/', 'contrib/' and 'include/' within a 'Engine/vendor/Assimp' folder and I made a premake file in order to build it all within the engine and make use of it (because I'm using premake as a project generator/builder).

The issue is that I'm getting 5 linker errors that I assume it is because of not including some file in the premake. The linker errors are the next ones:

![image](https://user-images.githubusercontent.com/11302677/123560466-933f3900-d7a2-11eb-9f1b-a426e02a2017.png)

So the functions that seems to give problems are 3, and even if I try to include the files they are in in the project, they give even more linker errors that I finally cannot solve by keep adding or including files, so I don't really know how to fix this, I tried to check in the documentation for some lights but I found nothing. Also I've checked some posts in github and forums about building assimp with premake but none had nothing for me to solve this.

The premake file I'm using to do this is the next: https://gist.github.com/lucho1/977542b209e4c039cc90ac0041004365

And note that if I comment some definition like "ASSIMP_BUILD_NO_IFC_IMPORTER", it will also trigger a linker error for some function IFC uses (in this case for a StepFile function), so this is why I'm assuming I'm including something incorrectly, because if I try to build it with more importers, it will keep triggering linker errors.

Also, I don't really have an extensive experience on this kind of matters, so I'm surely doing something wrong, but I cannot manage to find it and I've been like a week searching for it (it's frustrating), does anyone sees what it is?

Thank you a lot :)

**Comment by lucho1** [comment] 2021-06-30 17:33
I made a related StackOverflow question: https://stackoverflow.com/questions/68182193/linker-errors-when-building-assimp-with-premake/68187745?noredirect=1#comment120532195_68187745

**Comment by kimkulling** [comment] 2021-07-25 10:12
You forgot to add the GenerateBoundingBox Post-Process. This is one issue I found.

I will continue to look onto the issue.

**Comment by kimkulling** [comment] 2022-06-14 06:41
I guess this issue was related to a problem with correct exports, which is fixed in the latest release. It would be great if you could just retry this with 5.2.4. 

If the issue is still there just reopen this issue.

**Closed by kimkulling** 2022-06-14 06:41 UTC
Labels: Question
