### ISSUE TITLE
Error loading bundled test .lwo model: "Unable to build a valid node graph"

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#2925] opened 2020-01-18 09:12 UTC
Get error when attempting to load bundled test model file:
[`test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Laserbeam.lwo`](https://github.com/assimp/assimp/blob/master/test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Laserbeam.lwo)

[Updated Feb 2023] also these files:
[LWO/LWOB/ConcavePolygon.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/ConcavePolygon.lwo)
[LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo)
[LWO/LWOB/sphere_with_mat_gloss_10pc.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo)
[LWO/LWOB/sphere_with_mat_gloss_50pc.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo)

Error message is: `LWO: Unable to build a valid node graph`

Anyone else seeing this?

**Comment by SamuelTS** [comment] 2020-01-18 11:35
Same error here.

**Comment by turol** [comment] 2020-01-20 11:47
Same error here. File has not been changed since its introduction. @tellypresence can you bisect assimp to see if it ever worked?

**Comment by kimkulling** [comment] 2020-01-23 10:42
This error is an old one. We already have this issue in the issue-tracker I need to check.

**Comment by tellypresence** [comment] 2023-02-02 05:07
Same error for models:
[LWO/LWOB/ConcavePolygon.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/ConcavePolygon.lwo)
[LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/MappingModes/bluewithcylindrictexz.lwo)
[LWO/LWOB/sphere_with_mat_gloss_10pc.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo)
[LWO/LWOB/sphere_with_mat_gloss_50pc.lwo](https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo)

Error message is: LWO: Unable to build a valid node graph

**Comment by turol** [comment] 2023-02-23 16:20
Duplicate of #1196

**Closed by turol** 2023-02-23 16:20 UTC
Labels: Bug, LWO

**Comment by tellypresence** [comment] 2023-03-14 04:38
Some assimp bisecting for future reference:

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "ConcavePolygon.lwo"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/ffc95162ecdcf9bdaecfc3ebb6ba970e1a74aedb">ffc9516</a><br>
28 Feb 2017</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/ConcavePolygon.lwo">test/models/LWO/LWOB/ConcavePolygon.lwo</a></td><td>Load error: <tt>LWO: Unable to build a valid node graph</tt></td></tr>
</table>

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "bluewithcylindrictexz.lwo"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/ffc95162ecdcf9bdaecfc3ebb6ba970e1a74aedb">ffc9516</a><br>
28 Feb 2017</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/bluewithcylindrictexz.lwo">test/models/LWO/LWOB/bluewithcylindrictexz.lwo</a></td><td>Load error: <tt>LWO: Unable to build a valid node graph</tt></td></tr>
</table>

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "sphere_with_mat_gloss_10pc.lwo"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/ffc95162ecdcf9bdaecfc3ebb6ba970e1a74aedb">ffc9516</a><br>
28 Feb 2017</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo">test/models/LWO/LWOB/sphere_with_mat_gloss_10pc.lwo</a></td><td>Load error: <tt>LWO: Unable to build a valid node graph</tt></td></tr>
</table>

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "sphere_with_mat_gloss_50pc.lwo"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/ffc95162ecdcf9bdaecfc3ebb6ba970e1a74aedb">ffc9516</a><br>
28 Feb 2017</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo">test/models/LWO/LWOB/sphere_with_mat_gloss_50pc.lwo</a></td><td>Load error: <tt>LWO: Unable to build a valid node graph</tt></td></tr>
</table>

<table>
<tr><th colspan=3>Bisecting assimp for troubleshooting "QuickDraw--Laserbeam.lwo"</th></tr>
<tr><th>Assimp commit hash</th><th>3D model file</th><th>Result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/commit/ffc95162ecdcf9bdaecfc3ebb6ba970e1a74aedb">ffc9516</a><br>
28 Feb 2017</td><td><a href="https://github.com/assimp/assimp/blob/master/test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Laserbeam.lwo">test/models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Laserbeam.lwo</a></td><td>Load error: <tt>LWO: Unable to build a valid node graph</tt></td></tr>
</table>
