### ISSUE TITLE
Wrong node transformations when importing FBX and DAE files

### ISSUE THREAD

**Issue by Trylz** [assimp/assimp#1306] opened 2017-06-12 02:24 UTC
When trying to inport DAE and FBX files using 3ds max 2016, some nodes seems to have wrong transforms.
Using the aiProcess_PreTransformVertices flag or manually accumulating node transforms give me the same results. In the case of  FBX its look like only the last mesh of the scene is always wrong (i tried others scenes)

OBJ reference:  
![reference-obj](https://user-images.githubusercontent.com/9217999/27017194-b03a1c0e-4ef4-11e7-8cd6-5fc3ed5eece7.png)  

FBX:  
![wrong_node-fbx](https://user-images.githubusercontent.com/9217999/27017200-b39c57ea-4ef4-11e7-83c9-6c9fec3bdfd1.png)  

DAE:  
![wrong_node-dae](https://user-images.githubusercontent.com/9217999/27017201-b572c3c4-4ef4-11e7-8b54-7bd78894d8d5.png)

**Comment by iKlsR** [comment] 2017-06-16 00:43
If you're going to file an issue, share any file(s) and or specific code snippets used so someone can reproduce and possibly assist. Otherwise this is just noise and will help nobody.

**Comment by Trylz** [comment] 2017-06-16 03:31
Hey,


Sorry for the missing information. Any Fbx / Dae file from 3ds max should reproduce it. If not it's  not an Assimp issue.

________________________________
De : Ricardo Lovelace <notifications@github.com>
Envoyé : 15 juin 2017 20:43:27
À : assimp/assimp
Cc : Trylz; Author
Objet : Re: [assimp/assimp] Wrong node transformations when importing FBX and DAE files (#1306)


If you're going to file an issue, share any file(s) and or specific code snippets used so someone can reproduce and possibly assist. Otherwise this is just noise and will help nobody.

**Comment by kimkulling** [comment] 2017-07-10 07:22
Do you have a small example, please?

**Comment by Trylz** [comment] 2017-07-10 23:22
Sure. Here a zip with the model files corresponding to the screenshots and some code snippet.
The loading is done in BaseModel::loadModel(const std::string& path).
[Files.zip](https://github.com/assimp/assimp/files/1137315/Files.zip)


Thank you :)

**Comment by rickomax** [comment] 2017-07-15 13:57
Possibly related to:
https://github.com/assimp/assimp/issues/1127

**Comment by Trylz** [comment] 2017-10-18 16:00
Is there something planned for that ? if not where i could check in the source ? Its look like the problem is shared by collada and fbx models

**Comment by mesilliac** [comment] 2018-02-21 13:48
This doesn't seem to be a geometric transformations issue. Actually i can't reproduce - the FBX file seems to be loaded fine by assimp, and exports to OBJ fine, including the missing model here.

Possibly it was fixed inadvertently somewhere down the track?

The DAE file also loads and converts fine, but the final scale is 100 times smaller... the DAE file says its units are in centimetres, so probably it gets converted to metres internally (as this is the default for DAE). The OBJ file has no information about scale. The FBX scale probably is not converted internally, as centimetres is the default scale for FBX. Thus the FBX andOBJ are loaded with vertex positions in the 100's, and the DAE is loaded with vertex positions in the 1.0's.

I think that's actually a feature, so that people get what they expect when they load the respective file format.

**Comment by Trylz** [comment] 2018-02-21 20:15
The FBX file is now correctly loaded :)
For the DAE file yes the units seems internally converted. I agree this is a feature. We should be able to not import file units.

**Comment by kimkulling** [comment] 2018-03-30 09:06
Closed by the post-transform fix for the FBX-Importer ( see https://github.com/assimp/assimp/pull/1806 )

**Closed by kimkulling** 2018-03-30 09:06 UTC
Labels: bug
