### ISSUE TITLE
Bug: "Expected end of <source> element" when importing Collada file

### ISSUE THREAD

**Issue by Feuertopf** [assimp/assimp#3957] opened 2021-06-14 12:58 UTC
**Describe the bug**
I'm trying to import a Collada file downloaded from this address:
https://3dwarehouse.sketchup.com/model/uc355dcb8-90bd-4278-8fe1-f35647b04795/Disneyland-Paris-Sleeping-Beauty-Castle-3D-model
For convenience, I have attached this file:
[assimp-bugreport.zip](https://github.com/assimp/assimp/files/6648412/assimp-bugreport.zip)

I'm using Assimp 5.0.0 x64 in a C# program via AssimpNet. Using Sysinternals Process Monitor I verified that my program is actually loading the correct 5.0.0 assimp.dll file. I got that dll via vcpkg.

**Expected behavior**
The file should be imported correctly.

**Actual behaviour**
Import crashes with the error message:

Error importing file: Collada: c:\3dmodels\untitled.dae - Expected end of <source> element.

Please let me know if I can help in any way to solve this.

**Comment by ts-stevem** [comment] 2021-06-15 00:54
That model provides 5 different downloads (for sketchup 2017, 2018, 2019, 2020, 2021) -- do all 5 suffer from this problem?

**Comment by Feuertopf** [comment] 2021-06-15 10:59
I used the "Google Earth KMZ" download and then unzipped that file to get the Collada file. This bug  report is about that collada file.

Is Assimp even able to load Sketchup files? When I try to load the Sketchup file, I get "No suitable reader found for the file format of file". When I unzip the Sketchup file and select the model.dat file, the same thing happens.

**Comment by kimkulling** [comment] 2021-06-16 08:22
Ok, I need to take a look. The first thing you can try is to switch to the latest master, because we have reimplemented the Collada-Loading process by switching to a newer XML-parser.

**Comment by Feuertopf** [comment] 2021-06-17 04:36
Thank you! Please let me know if I can help in any way.

Unfortunately, there's no good way for me to test the latest master within my project because AssimpNet is not compatible with that. (crashes)

**Comment by kimkulling** [comment] 2021-07-26 08:49
Hi,

just check the model. There is a crash caused by it, which I will fix. As I said before the parsing is fixed on the current master. I will have to check when we will be able to release a new assimp-version and provide the latest master in Assimp.Net.

Kim

**Closed** 2021-07-26 09:14 UTC
Labels: Bug
