### ISSUE TITLE
FBX loading failed since last update

### ISSUE THREAD

**Issue by mgerhardy** [assimp/assimp#1089] opened 2016-11-28 20:12 UTC
[chr_skelett2.zip](https://github.com/assimp/assimp/files/617358/chr_skelett2.zip)

'FBX-Tokenize (offset 0xa8) failed ReadString, unexpected NUL character in string'

**Comment by kimkulling** [comment] 2016-11-29 10:33
Thanks for the report, It worked in the last version?

**Comment by mgerhardy** [comment] 2016-11-29 11:02
it works in the debian testing version:
Package: libassimp-dev
Source: assimp
Version: 3.3.1~dfsg-4

And it also worked with a version from git from 06. November.

**Comment by kimkulling** [comment] 2016-12-01 15:04
Hi,

I can reproduce the issue. I will start to have a look onto it.

**Comment by ongamex** [comment] 2016-12-01 15:07
I had the same issue last night. One of the latest commits (the one about 64bit support). Breaks the importer.

Besides that I've got a model which imports the animation data incorrectly. I'll provide a more information later.

**Comment by kimkulling** [comment] 2016-12-01 17:40
Do you have a hash for this one?

**Comment by ongamex** [comment] 2016-12-01 17:50
This is the commit that breaks the thing for me file:
2505f0226314ee1230d0acdf64a6671e95f3dac2

Here is my file (if you dare to download it, it takes a few retires) http://www.mediafire.com/file/dtu494re2ng43uy/Mario+Galaxy+Full+Animations.zip
(the other crash that I was talking about seems to be fixed in a latter commit)

**Comment by kimkulling** [comment] 2016-12-01 17:57
You are right. Seems to be an issue with reading out the size of words. Somhow the FBX-loader things he works on a 64-bit build. Unfortunately it is a 32-bit build and so the sizes were wrong. I have a small workaround to reenable the import again.

**Comment by kimkulling** [comment] 2016-12-01 18:34
And thanks for figuring this out!

**Comment by kimkulling** [comment] 2016-12-02 17:01
Should be fixed now. PLease reopen if this is still an issue.

**Comment by ongamex** [comment] 2016-12-02 17:52
I'm not sure if this is suitable for the same issue or not. With my Mario Galaxy model(linked above)
I get an error In that code:

```
            const size_t id0 = next_pos[ i ]>0 ? next_pos[ i ] - 1 : 0;
            const size_t id1 = next_pos[ i ] == ksize ? ksize - 1 : next_pos[ i ]; // crashes below with ksize = 0, i =0 and next_pos[i] is some bizarre huge number (i suppouse due to wrong read operation earlier). I tried to debug it but I have no understanding of FBX file format and I wasn't able to find where the animation data is read.

            // use lerp for interpolation
            const KeyValueList::value_type valueA = std::get<1>(kfl)->at( id0 );
            const KeyValueList::value_type valueB = std::get<1>(kfl)->at( id1 ); // throws here because of id1

```

**Comment by kimkulling** [comment] 2016-12-03 09:06
I would risk it :-). Thanks for the report!

**Comment by ongamex** [comment] 2016-12-05 19:51
Sorry for troubling you again, but is this issue still open? as i did not create this particular issue I cannot reopen it.

**Comment by kimkulling** [comment] 2016-12-05 20:28
done :-)

**Comment by kimkulling** [comment] 2018-01-15 21:00
Shall be fixed now.

**Closed by kimkulling** 2018-01-15 21:00 UTC
