### ISSUE TITLE
FBX import fails

### ISSUE THREAD

**Issue by SGStino** [assimp/assimp#838] opened 2016-03-27 21:39 UTC
I'm trying to load various of my fbx files in assimp viewer, but none of them seem to load. Most  (coming from 3dsmax) 

show up without any meshes and an error in the log:
`FBX-DOM (TOK_KEY, offset 0xccb00) source object for connection does not exist`
`FBX-Parser did not find required element "Binormal"`
`FBX-DOM (TOK_KEY, offset 0xc97d0) failed to read source object for incoming Model link, ignoring`
while other files (coming from maya) throw the exception 
`Error, T15852: FBX-Tokenize (offset 0x34) block offset is out of range`

Example files:
[fbx_exports.zip](https://github.com/assimp/assimp/files/191139/fbx_exports.zip)

PS: i've scanned over the source code and i've noticed assimp is not using the fbx sdk, is there a specific reason (licenses?) for that?

**Comment by echorebel** [comment] 2016-04-13 21:07
I have similar issue with `[ error ] ofxAssimpModelLoader: loadModel(): FBX-Tokenize (offset 0x34) block offset is out of range` while trying fbx from cinema

**Comment by TheOrestes** [comment] 2016-11-14 15:55
Was facing the exact same issue today, I just changed the FBX file format version to FBX2014/15 & it worked. Earlier I was using 2016/17 version.

**Comment by rickomax** [comment] 2017-07-19 19:37
I had this issue too, and seems it´s caused by the first FBX data chunk be using 64 bits addresses, instead of 32 bits. I just have to figure out how if the model is using 64 or 32 bits, so I can try to make a fix.

**Comment by rickomax** [comment] 2017-07-19 20:55
Fixed this, will make a pull-request soon. I was able to load all your models.

**Comment by kimkulling** [comment] 2018-02-24 10:37
Fixed now on latest master.

**Closed by kimkulling** 2018-02-24 10:37 UTC
