### ISSUE TITLE
Loader(s) *::InternReadFile assigning ownership of a user created reference( IOStream* returned by IOSystem::Open) to a std::unique_ptr

### ISSUE THREAD

**Issue by cgrant78** [assimp/assimp#5672] opened 2024-07-17 03:59 UTC
**Describe the technical debt**
In several of the Assimp loader InternReadFile implementation, the pointer returned by a potential custom IOSystem::Open method, that is, a custom IOStream is being used to initialize a std::unique_ptr. This 'transfers ownership' of that memory to the std::unique_ptr which will attempt to cleanup up the object when the InternReadFile method return. 

**Better solution**
The expectation is that the memory resource and subsequent ownership is the responsibility of the caller. The memory being referenced by the IOStream instance, could have been created from a custom allocator with privately defined deallocation behavior, so to assume ownership of a resource that was not created by library seems worrisome. Furthermore, this behavior is not consistent across the library as there are places where IOSystem::Open is called and no ownership is assumed, which seems to be the correct behavior that is required to prevent potential memory corruption and application termination.

**Comment by turol** [comment] 2024-07-20 17:28
Duplicate of #1761.

**Closed by turol** 2024-07-20 17:28 UTC
Labels: Techdebt
