### ISSUE TITLE
Assimp does not support gltf format with KHR_draco_mesh_compression extension.

### ISSUE THREAD

**Issue by runforu** [assimp/assimp#2963] opened 2020-01-27 20:34 UTC
As the mentioned in the title, assimp does not support compressed gltf file format.

**Comment by RichardTea** [comment] 2020-01-28 05:15
This is a duplicate of #2195 

Are you working on adding this support?

**Comment by kimkulling** [comment] 2020-01-28 08:21
I made some basic investigations, not more.

**Comment by kimkulling** [comment] 2020-01-28 08:22
I will close this one, let's use the other to track the feature request.

**Closed by kimkulling** 2020-01-28 08:22 UTC
Labels: Feature-Request, glTF2.0
