### ISSUE TITLE
Insufficient material descriptions

### ISSUE THREAD

**Issue by mjgalindo** [assimp/assimp#1927] opened 2018-04-28 09:01 UTC
I might be using assimp wrong, but I can't seem to find all the information necessary to load materials.
I find that the properties that are loaded into `mMaterials` are not enough to describe materials either from blender scenes (`.blend` and exported to `.fbx`, `.3ds`, and  `.dae`). For starters, the enum `aiShadingMode` enum is not enough to describe materials, but then again, I find it's only set for some materials in `.fbx` files, never in blender (though the description of `aiShadingMode` specifies that they were taken from blender).

As far as I can see, there is no way to tell materials apart, at most I can get diffuse, specular and reflective components and guess at what shading mode to use, since I can't trust the shading mode flag. What about principled bsdf in blender or pbr shader in whatever other formats?

Also, the properties set while loading each file format are different, blender being the worst since it sets a lot of properties that basically repeat the "basic" properties (such as `$clr.diffuse` or `$clr.specular`). In this way, how is assimp helping me use a single interface for all the different 3D formats?

I really think I'm missing something here, since it seems like I'm the only one that has this kind of problem.

**Comment by kimkulling** [comment] 2018-10-05 19:35
You are right, we need to improve the documentation and the API.

**Comment by kimkulling** [comment] 2021-04-14 09:02
We added PBR-material descriptions, made improvements to work with FBX and Collada properly. So from my point of view we will close this issue. 
If you see a gap between the existing Material API and your requirements: please add an feature-request into our database. Caused by my spare time I have forgotten a lot of older feature-requests which would be really useful but hard to do caused by my spare time. 

Getting this into my focus will help a lot to get these gaps filled. Sorry for that!

**Closed by kimkulling** 2021-04-14 09:02 UTC
Labels: Feature-Request
